<script setup lang="ts">
import { ref, reactive, computed, onMounted, onUnmounted, watch, nextTick } from 'vue'
import { useRouter } from 'vue-router'
import { connection, RESOURCE_TYPES } from '../state'
import { apiFetch } from '../api'
import {
  getCreateUrl,
  getDetailUrl,
  getUpdateUrl,
  getDeleteUrl,
  getContentType,
  extractCSAPIFeature,
  getCSAPIResourceType,
} from '../csapi-bridge'

// OpenLayers
import OlMap from 'ol/Map'
import View from 'ol/View'
import TileLayer from 'ol/layer/Tile'
import VectorLayer from 'ol/layer/Vector'
import VectorSource from 'ol/source/Vector'
import OSM from 'ol/source/OSM'
import { fromLonLat } from 'ol/proj'
import OlFeature from 'ol/Feature'
import OlPoint from 'ol/geom/Point'
import { Style, Circle as CircleStyle, Fill, Stroke, Text as OlText } from 'ol/style'

const router = useRouter()

watch(
  () => connection.connected,
  (c) => { if (!c) router.push('/') },
  { immediate: true }
)

// ─── Types ───────────────────────────────────────────────

type OpType = 'CREATE' | 'READ' | 'UPDATE' | 'VERIFY' | 'DELETE'
type StepStatus = 'pending' | 'active' | 'running' | 'success' | 'fail' | 'skipped'

interface Step {
  id: number
  resourceType: string
  resourceLabel: string
  op: OpType
  status: StepStatus
  request?: { method: string; url: string; headers: Record<string, string>; body?: string }
  response?: { status: number; statusText: string; headers: Record<string, string>; body: string; rawError?: string }
  before?: any
  after?: any
  elapsed?: number
  error?: string
  coords?: [number, number]
}

// ─── Test Coordinates ────────────────────────────────────
const COORDS: Record<string, { create: [number, number]; update: [number, number] }> = {
  systems:           { create: [-77.0352, 38.8895], update: [-77.0502, 38.8893] },
  procedures:        { create: [-77.0366, 38.8977], update: [-77.0229, 38.8997] },
  deployments:       { create: [-77.0098, 38.8899], update: [-77.0440, 38.8916] },
  samplingFeatures:  { create: [-77.0479, 38.8813], update: [-77.0365, 38.8822] },
}

// ─── Test Payloads ───────────────────────────────────────

function makePayload(type: string, phase: 'create' | 'update'): any {
  const coords = COORDS[type]
  const c = coords ? coords[phase] : undefined
  const geom = c ? { type: 'Point', coordinates: c } : null

  const uid = phase === 'create'
    ? `urn:csapi-explorer:smoke-test:${type}:${Date.now()}`
    : createdUids[type]  // Reuse original UID on update — OSH requires it
  const name = phase === 'create'
    ? `Smoke Test ${type}`
    : `Smoke Test ${type} (updated)`

  const featureTypes: Record<string, string> = {
    systems: 'http://www.w3.org/ns/sosa/Platform',
    procedures: 'http://www.w3.org/ns/sosa/Procedure',
    deployments: 'http://www.w3.org/ns/sosa/Deployment',
    samplingFeatures: 'http://www.w3.org/ns/sosa/Sample',
  }

  if (['systems', 'procedures', 'deployments', 'samplingFeatures'].includes(type)) {
    return {
      type: 'Feature',
      properties: {
        featureType: featureTypes[type],
        name,
        uid,
        description: `Auto-generated by CRUD smoke test (${phase})`,
      },
      geometry: geom,
    }
  }

  if (type === 'datastreams') {
    return {
      name,
      outputName: 'smoke-test-output',
      schema: {
        obsFormat: 'application/json',
        recordSchema: {
          type: 'DataRecord',
          label: 'Smoke Test Record',
          fields: [
            { type: 'Quantity', label: 'Temperature', name: 'temp', uom: { code: 'Cel' } },
          ]
        }
      }
    }
  }

  if (type === 'observations') {
    return {
      phenomenonTime: new Date().toISOString(),
      resultTime: new Date().toISOString(),
      result: { temp: phase === 'create' ? 22.5 : 25.0 },
    }
  }

  if (type === 'controlStreams') {
    return {
      name,
      inputName: 'smoke-test-input',
      schema: {
        cmdFormat: 'application/json',
        recordSchema: {
          type: 'DataRecord',
          label: 'Smoke Test Command',
          fields: [
            { type: 'Boolean', label: 'Active', name: 'active' },
          ]
        }
      }
    }
  }

  if (type === 'commands') {
    return {
      issueTime: new Date().toISOString(),
      params: { active: phase === 'create' },
    }
  }

  return { name }
}

// ─── Step Building ───────────────────────────────────────

const PART1_TYPES = ['systems', 'procedures', 'deployments', 'samplingFeatures']
const PART2_TYPES = ['datastreams', 'observations', 'controlStreams', 'commands']
const PART1_OPS: OpType[] = ['CREATE', 'READ', 'UPDATE', 'VERIFY']  // No DELETE — Part 2 needs parents alive
const CRUD_OPS: OpType[] = ['CREATE', 'READ', 'UPDATE', 'VERIFY', 'DELETE']

function buildSteps(): Step[] {
  const steps: Step[] = []
  let id = 1
  // Phase 1: Part 1 CRUD without DELETE (keep parents alive for Part 2)
  for (const key of PART1_TYPES) {
    const info = RESOURCE_TYPES.find((r) => r.key === key)!
    for (const op of PART1_OPS) {
      steps.push({ id: id++, resourceType: key, resourceLabel: info.label, op, status: 'pending' })
    }
  }
  // Phase 2: Part 2 full CRUD (parents still exist)
  for (const key of PART2_TYPES) {
    const info = RESOURCE_TYPES.find((r) => r.key === key)!
    for (const op of CRUD_OPS) {
      steps.push({ id: id++, resourceType: key, resourceLabel: info.label, op, status: 'pending' })
    }
  }
  // Phase 3: Part 1 DELETE (cleanup after Part 2 is done)
  for (const key of PART1_TYPES) {
    const info = RESOURCE_TYPES.find((r) => r.key === key)!
    steps.push({ id: id++, resourceType: key, resourceLabel: info.label, op: 'DELETE', status: 'pending' })
  }
  return steps
}

// ─── Reactive State ──────────────────────────────────────

const steps = ref<Step[]>(buildSteps())
const currentStepIndex = ref(-1)
const running = ref(false)
const testStarted = ref(false)

const createdIds = reactive<Record<string, string>>({})
const createdUids = reactive<Record<string, string>>({})

const activeStep = computed(() =>
  currentStepIndex.value >= 0 && currentStepIndex.value < steps.value.length
    ? steps.value[currentStepIndex.value]
    : null
)

const completedCount = computed(() => steps.value.filter((s) => ['success', 'fail', 'skipped'].includes(s.status)).length)
const successCount = computed(() => steps.value.filter((s) => s.status === 'success').length)
const failCount = computed(() => steps.value.filter((s) => s.status === 'fail').length)
const skippedCount = computed(() => steps.value.filter((s) => s.status === 'skipped').length)
const hasMoreSteps = computed(() => currentStepIndex.value < steps.value.length - 1)
const isStepReady = computed(() => activeStep.value?.status === 'active')
const isStepDone = computed(() => activeStep.value && ['success', 'fail', 'skipped'].includes(activeStep.value.status))

// ─── Map ─────────────────────────────────────────────────

const mapContainer = ref<HTMLDivElement>()
let map: OlMap | null = null
const vectorSource = new VectorSource()

const TYPE_COLORS: Record<string, string> = {
  systems: '#3b82f6',
  procedures: '#f59e0b',
  deployments: '#8b5cf6',
  samplingFeatures: '#10b981',
  datastreams: '#ef4444',
  controlStreams: '#f97316',
  observations: '#06b6d4',
  commands: '#ec4899',
}

const TYPE_LABELS: Record<string, string> = {
  systems: 'S',
  procedures: 'P',
  deployments: 'D',
  samplingFeatures: 'F',
  datastreams: 'DS',
  controlStreams: 'CS',
  observations: 'O',
  commands: 'Cmd',
}

function markerStyle(resourceType: string, phase: 'create' | 'update' | 'ghost'): Style {
  const color = TYPE_COLORS[resourceType] || '#6b7280'
  const label = TYPE_LABELS[resourceType] || '?'
  const isGhost = phase === 'ghost'
  return new Style({
    image: new CircleStyle({
      radius: isGhost ? 7 : 12,
      fill: new Fill({ color: isGhost ? 'transparent' : color }),
      stroke: new Stroke({ color, width: isGhost ? 2 : 3, lineDash: isGhost ? [4, 4] : undefined }),
    }),
    text: new OlText({
      text: isGhost ? '' : label,
      fill: new Fill({ color: '#fff' }),
      font: 'bold 11px sans-serif',
      offsetY: 1,
    }),
  })
}

function initMap() {
  if (!mapContainer.value || map) return
  map = new OlMap({
    target: mapContainer.value,
    layers: [
      new TileLayer({ source: new OSM() }),
      new VectorLayer({ source: vectorSource }),
    ],
    view: new View({
      center: fromLonLat([-77.035, 38.890]),
      zoom: 14,
    }),
  })
}

function addMarker(resourceType: string, coords: [number, number], featureId: string, phase: 'create' | 'update') {
  const existing = vectorSource.getFeatureById(featureId)
  if (existing) vectorSource.removeFeature(existing)

  if (phase === 'update') {
    const oldCoords = COORDS[resourceType]?.create
    if (oldCoords) {
      const ghostId = featureId + '-ghost'
      const existingGhost = vectorSource.getFeatureById(ghostId)
      if (existingGhost) vectorSource.removeFeature(existingGhost)
      const ghost = new OlFeature({ geometry: new OlPoint(fromLonLat(oldCoords)) })
      ghost.setId(ghostId)
      ghost.setStyle(markerStyle(resourceType, 'ghost'))
      vectorSource.addFeature(ghost)
    }
  }

  const feature = new OlFeature({ geometry: new OlPoint(fromLonLat(coords)) })
  feature.setId(featureId)
  feature.setStyle(markerStyle(resourceType, phase))
  vectorSource.addFeature(feature)

  map?.getView().animate({ center: fromLonLat(coords), duration: 600 })
}

function removeMarker(featureId: string) {
  const f = vectorSource.getFeatureById(featureId)
  if (f) vectorSource.removeFeature(f)
  const g = vectorSource.getFeatureById(featureId + '-ghost')
  if (g) vectorSource.removeFeature(g)
}

function clearMap() {
  vectorSource.clear()
}

// ─── Preview: prepare what the step WILL do ──────────────

function prepareStepPreview(step: Step) {
  const contentType = getContentType(step.resourceType)

  switch (step.op) {
    case 'CREATE': {
      let parentId: string | undefined
      if (step.resourceType === 'datastreams' || step.resourceType === 'controlStreams') {
        parentId = createdIds['systems']
      }
      if (step.resourceType === 'observations') parentId = createdIds['datastreams']
      if (step.resourceType === 'commands') parentId = createdIds['controlStreams']

      const url = getCreateUrl(step.resourceType, parentId)
      const payload = makePayload(step.resourceType, 'create')
      step.request = {
        method: 'POST',
        url,
        headers: { 'Content-Type': contentType },
        body: JSON.stringify(payload, null, 2),
      }
      break
    }
    case 'READ':
    case 'VERIFY': {
      const id = createdIds[step.resourceType]
      if (id) {
        step.request = {
          method: 'GET',
          url: getDetailUrl(step.resourceType, id),
          headers: { 'Accept': contentType },
        }
      }
      break
    }
    case 'UPDATE': {
      const id = createdIds[step.resourceType]
      if (id) {
        const payload = makePayload(step.resourceType, 'update')
        step.request = {
          method: 'PUT',
          url: getUpdateUrl(step.resourceType, id),
          headers: { 'Content-Type': contentType, 'Accept': contentType },
          body: JSON.stringify(payload, null, 2),
        }
      }
      break
    }
    case 'DELETE': {
      const id = createdIds[step.resourceType]
      if (id) {
        step.request = {
          method: 'DELETE',
          url: getDeleteUrl(step.resourceType, id),
          headers: {},
        }
      }
      break
    }
  }
}

// ─── Step Execution ──────────────────────────────────────

async function executeCurrentStep() {
  const step = activeStep.value
  if (!step || step.status !== 'active') return

  step.status = 'running'
  const start = performance.now()

  const contentType = getContentType(step.resourceType)

  try {
    switch (step.op) {
      case 'CREATE': {
        let parentId: string | undefined
        if (step.resourceType === 'datastreams' || step.resourceType === 'controlStreams') {
          parentId = createdIds['systems']
          if (!parentId) { markSkipped(step, 'No parent system created — skipping', start); return }
        }
        if (step.resourceType === 'observations') {
          parentId = createdIds['datastreams']
          if (!parentId) { markSkipped(step, 'No parent datastream created — skipping', start); return }
        }
        if (step.resourceType === 'commands') {
          parentId = createdIds['controlStreams']
          if (!parentId) { markSkipped(step, 'No parent control stream created — skipping', start); return }
        }

        const url = getCreateUrl(step.resourceType, parentId)
        const payload = makePayload(step.resourceType, 'create')
        const bodyStr = JSON.stringify(payload, null, 2)

        // Only send Content-Type, NOT Accept — OSH may reject Accept: application/geo+json
        // apiFetch defaults Accept to application/json which works fine
        step.request = {
          method: 'POST', url,
          headers: { 'Content-Type': contentType },
          body: bodyStr,
        }
        step.before = null

        const resp = await apiFetch(url, {
          method: 'POST',
          headers: { 'Content-Type': contentType },
          body: bodyStr,
        })

        setResponse(step, resp)

        if (!resp.ok) {
          markFail(step, resp.error || `${resp.status} ${resp.statusText}`, start)
          return
        }

        // Extract ID from Location header
        const location = resp.headers['location'] || ''
        const id = location.split('/').pop() || ''
        if (id) createdIds[step.resourceType] = id

        // Store the UID so UPDATE can include it (OSH requires it)
        const payload2 = JSON.parse(bodyStr)
        if (payload2?.properties?.uid) createdUids[step.resourceType] = payload2.properties.uid

        step.after = resp.data || { _smokeTest: true, id, location }
        step.status = 'success'

        // Map
        const coords = COORDS[step.resourceType]?.create
        if (coords && id) {
          step.coords = coords
          addMarker(step.resourceType, coords, `smoke-${step.resourceType}`, 'create')
        }
        break
      }

      case 'READ': {
        const id = createdIds[step.resourceType]
        if (!id) { markSkipped(step, 'No ID from CREATE — skipping', start); return }

        const url = getDetailUrl(step.resourceType, id)
        step.request = { method: 'GET', url, headers: { 'Accept': contentType } }

        const resp = await apiFetch(url, { method: 'GET', headers: { 'Accept': contentType } })
        setResponse(step, resp)

        if (!resp.ok) {
          markFail(step, resp.error || `${resp.status} ${resp.statusText}`, start)
        } else {
          step.before = null
          step.after = resp.data
          step.status = 'success'
          const coords = COORDS[step.resourceType]?.create
          if (coords) step.coords = coords
        }
        break
      }

      case 'UPDATE': {
        const id = createdIds[step.resourceType]
        if (!id) { markSkipped(step, 'No ID from CREATE — skipping', start); return }

        // Fetch current state as "before"
        const readUrl = getDetailUrl(step.resourceType, id)
        const readResp = await apiFetch(readUrl, { method: 'GET', headers: { 'Accept': contentType } })
        step.before = readResp.data

        const url = getUpdateUrl(step.resourceType, id)
        const payload = makePayload(step.resourceType, 'update')
        const bodyStr = JSON.stringify(payload, null, 2)

        step.request = {
          method: 'PUT', url,
          headers: { 'Content-Type': contentType, 'Accept': contentType },
          body: bodyStr,
        }

        const resp = await apiFetch(url, {
          method: 'PUT',
          headers: { 'Content-Type': contentType, 'Accept': contentType },
          body: bodyStr,
        })
        setResponse(step, resp)

        if (!resp.ok) {
          markFail(step, resp.error || `${resp.status} ${resp.statusText}`, start)
        } else {
          step.after = resp.data || payload
          step.status = 'success'
          const coords = COORDS[step.resourceType]?.update
          if (coords) {
            step.coords = coords
            addMarker(step.resourceType, coords, `smoke-${step.resourceType}`, 'update')
          }
        }
        break
      }

      case 'VERIFY': {
        const id = createdIds[step.resourceType]
        if (!id) { markSkipped(step, 'No ID from CREATE — skipping', start); return }

        const url = getDetailUrl(step.resourceType, id)
        step.request = { method: 'GET', url, headers: { 'Accept': contentType } }

        const resp = await apiFetch(url, { method: 'GET', headers: { 'Accept': contentType } })
        setResponse(step, resp)

        if (!resp.ok) {
          markFail(step, resp.error || `${resp.status} ${resp.statusText}`, start)
        } else {
          const updateStep = steps.value.find(
            (s) => s.resourceType === step.resourceType && s.op === 'UPDATE'
          )
          step.before = updateStep?.after || null
          step.after = resp.data
          step.status = 'success'
        }
        break
      }

      case 'DELETE': {
        const id = createdIds[step.resourceType]
        if (!id) { markSkipped(step, 'No ID from CREATE — skipping', start); return }

        const readUrl = getDetailUrl(step.resourceType, id)
        const readResp = await apiFetch(readUrl, { method: 'GET', headers: { 'Accept': contentType } })
        step.before = readResp.data

        const url = getDeleteUrl(step.resourceType, id)
        step.request = { method: 'DELETE', url, headers: {} }

        const resp = await apiFetch(url, { method: 'DELETE' })
        setResponse(step, resp)

        if (!resp.ok) {
          markFail(step, resp.error || `${resp.status} ${resp.statusText}`, start)
        } else {
          step.after = null
          step.status = 'success'
          delete createdIds[step.resourceType]
          removeMarker(`smoke-${step.resourceType}`)
        }
        break
      }
    }
  } catch (err: any) {
    step.status = 'fail'
    step.error = err.message || 'Unknown error'
  }

  step.elapsed = performance.now() - start
}

function setResponse(step: Step, resp: any) {
  step.response = {
    status: resp.status,
    statusText: resp.statusText,
    headers: resp.headers,
    body: resp.data ? JSON.stringify(resp.data, null, 2) : (resp.error || ''),
    rawError: resp.error || undefined,
  }
}

function markSkipped(step: Step, msg: string, start: number) {
  step.status = 'skipped'
  step.error = msg
  step.elapsed = performance.now() - start
}

function markFail(step: Step, msg: string, start: number) {
  step.status = 'fail'
  step.error = msg
  step.elapsed = performance.now() - start
}

// ─── Controls ────────────────────────────────────────────

function beginTest() {
  testStarted.value = true
  currentStepIndex.value = 0
  const step = steps.value[0]
  step.status = 'active'
  prepareStepPreview(step)
}

async function executeAndWait() {
  running.value = true
  await executeCurrentStep()
  running.value = false
}

function advanceToNextStep() {
  if (!hasMoreSteps.value) return
  currentStepIndex.value++
  const step = steps.value[currentStepIndex.value]
  step.status = 'active'
  prepareStepPreview(step)
}

function skipCurrentStep() {
  const step = activeStep.value
  if (!step) return
  step.status = 'skipped'
  step.error = 'Manually skipped'
  step.elapsed = 0
}

async function abortAndCleanup() {
  running.value = true
  const deleteOrder = ['commands', 'controlStreams', 'observations', 'datastreams', 'samplingFeatures', 'deployments', 'procedures', 'systems']
  for (const type of deleteOrder) {
    const id = createdIds[type]
    if (!id) continue
    try {
      const url = getDeleteUrl(type, id)
      await apiFetch(url, { method: 'DELETE' })
      delete createdIds[type]
      removeMarker(`smoke-${type}`)
    } catch { /* best effort */ }
  }
  running.value = false
}

function resetTest() {
  steps.value = buildSteps()
  currentStepIndex.value = -1
  testStarted.value = false
  running.value = false
  for (const key of Object.keys(createdIds)) delete createdIds[key]
  for (const key of Object.keys(createdUids)) delete createdUids[key]
  clearMap()
}

function selectStep(step: Step) {
  // Only allow viewing completed/active steps
  const idx = steps.value.indexOf(step)
  if (idx <= currentStepIndex.value) {
    currentStepIndex.value = idx
  }
  if (step.coords && map) {
    map.getView().animate({ center: fromLonLat(step.coords), duration: 400 })
  }
}

// ─── Formatting helpers ──────────────────────────────────

function opBadgeClass(op: OpType): string {
  return { CREATE: 'op-create', READ: 'op-read', UPDATE: 'op-update', VERIFY: 'op-verify', DELETE: 'op-delete' }[op]
}

function statusIcon(status: StepStatus): string {
  return {
    pending: 'pi pi-circle',
    active: 'pi pi-arrow-right',
    running: 'pi pi-spin pi-spinner',
    success: 'pi pi-check-circle',
    fail: 'pi pi-times-circle',
    skipped: 'pi pi-minus-circle',
  }[status]
}

function statusColor(status: StepStatus): string {
  return {
    pending: '#94a3b8',
    active: '#3b82f6',
    running: '#3b82f6',
    success: '#16a34a',
    fail: '#dc2626',
    skipped: '#f59e0b',
  }[status]
}

function formatMs(ms?: number): string {
  if (ms == null) return ''
  return ms < 1000 ? `${Math.round(ms)}ms` : `${(ms / 1000).toFixed(1)}s`
}

const groupedSteps = computed(() => {
  const groups: { type: string; label: string; steps: Step[] }[] = []
  let current: (typeof groups)[0] | null = null
  for (const step of steps.value) {
    if (!current || current.type !== step.resourceType) {
      current = { type: step.resourceType, label: step.resourceLabel, steps: [] }
      groups.push(current)
    }
    current.steps.push(step)
  }
  return groups
})

// ─── Auto-scroll ─────────────────────────────────────────

function scrollToActive(el: HTMLElement) {
  nextTick(() => {
    el.scrollIntoView({ behavior: 'smooth', block: 'nearest' })
  })
}

// ─── Lifecycle ───────────────────────────────────────────

onMounted(() => { nextTick(() => initMap()) })
onUnmounted(() => { map?.setTarget(undefined); map = null })
</script>

<template>
  <div class="smoke-test">
    <!-- Top bar -->
    <div class="smoke-toolbar">
      <div class="toolbar-left">
        <h2><i class="pi pi-bolt"></i> CRUD Smoke Test</h2>
        <span v-if="testStarted" class="progress-badge">
          Step {{ currentStepIndex + 1 }}/{{ steps.length }} —
          <span style="color:#16a34a">{{ successCount }} pass</span>
          <span v-if="failCount" style="color:#dc2626"> · {{ failCount }} fail</span>
          <span v-if="skippedCount" style="color:#f59e0b"> · {{ skippedCount }} skip</span>
        </span>
      </div>
      <div class="toolbar-right">
        <!-- Fixed-width action slot so buttons never shift -->
        <div class="action-slot">
          <button v-if="!testStarted" class="btn btn-primary" @click="beginTest">
            <i class="pi pi-play"></i> Begin Test
          </button>
          <button v-else-if="isStepReady" class="btn btn-execute" @click="executeAndWait" :disabled="running">
            <i class="pi pi-bolt"></i> Execute Step
          </button>
          <button v-else-if="isStepDone && hasMoreSteps" class="btn btn-primary" @click="advanceToNextStep">
            <i class="pi pi-arrow-right"></i> Next Step
          </button>
          <span v-else-if="isStepDone && !hasMoreSteps" class="done-badge">
            <i class="pi pi-check-circle"></i> Test Complete
          </span>
          <span v-else class="btn-placeholder"></span>
        </div>

        <!-- Fixed-width skip slot -->
        <div class="action-slot action-slot-sm">
          <button v-if="isStepReady" class="btn btn-secondary" @click="skipCurrentStep">
            <i class="pi pi-angle-double-right"></i> Skip
          </button>
          <span v-else class="btn-placeholder"></span>
        </div>

        <div class="toolbar-divider"></div>

        <!-- Always-present utility buttons with fixed slots -->
        <div class="action-slot action-slot-cleanup">
          <button v-if="testStarted" class="btn btn-danger" @click="abortAndCleanup" :disabled="running">
            <i class="pi pi-trash"></i> Cleanup
          </button>
          <span v-else class="btn-placeholder"></span>
        </div>
        <button class="btn btn-secondary" @click="resetTest" :disabled="running">
          <i class="pi pi-refresh"></i> Reset
        </button>
      </div>
    </div>

    <!-- Tri-panel -->
    <div class="panels">
      <!-- LEFT: Test Plan -->
      <div class="panel panel-plan">
        <div class="panel-header">Test Plan</div>
        <div class="plan-list">
          <div v-for="group in groupedSteps" :key="group.type" class="plan-group">
            <div class="plan-group-label">{{ group.label }}</div>
            <div
              v-for="step in group.steps"
              :key="step.id"
              :ref="(el) => { if (step === activeStep && el) scrollToActive(el as HTMLElement) }"
              class="plan-step"
              :class="{ active: step === activeStep, clickable: steps.indexOf(step) <= currentStepIndex }"
              @click="selectStep(step)"
            >
              <i :class="statusIcon(step.status)" :style="{ color: statusColor(step.status) }"></i>
              <span class="op-badge" :class="opBadgeClass(step.op)">{{ step.op }}</span>
              <span v-if="step.elapsed != null" class="step-time">{{ formatMs(step.elapsed) }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- CENTER: Request / Response -->
      <div class="panel panel-detail">
        <div class="panel-header">Request / Response</div>

        <!-- Not started -->
        <div v-if="!testStarted" class="panel-empty">
          <div class="empty-hero">
            <i class="pi pi-bolt" style="font-size:2rem;color:#3b82f6"></i>
            <p>Click <b>Begin Test</b> to start the CRUD smoke test.</p>
            <p class="empty-sub">Each step requires your approval before executing.<br>
              You'll see a preview of the request, then click <b>Execute Step</b> to send it.</p>
          </div>
        </div>

        <!-- Active step content -->
        <div v-else-if="activeStep" class="detail-content">
          <!-- Step header -->
          <div class="step-header-card">
            <span class="op-badge op-badge-lg" :class="opBadgeClass(activeStep.op)">{{ activeStep.op }}</span>
            <span class="step-resource-label">{{ activeStep.resourceLabel }}</span>
            <span v-if="activeStep.status === 'running'" class="running-indicator">
              <i class="pi pi-spin pi-spinner"></i> Executing...
            </span>
            <span v-if="activeStep.status === 'active'" class="ready-indicator">
              Ready — review below, then click Execute Step
            </span>
            <span v-if="activeStep.status === 'success'" class="success-indicator">
              <i class="pi pi-check-circle"></i> Success
            </span>
            <span v-if="activeStep.status === 'fail'" class="fail-indicator">
              <i class="pi pi-times-circle"></i> Failed
            </span>
            <span v-if="activeStep.status === 'skipped'" class="skip-indicator">
              <i class="pi pi-minus-circle"></i> Skipped
            </span>
            <span v-if="activeStep.elapsed != null" class="elapsed">{{ formatMs(activeStep.elapsed) }}</span>
          </div>

          <!-- Request preview / actual -->
          <div v-if="activeStep.request" class="detail-section">
            <div class="section-label">
              {{ activeStep.status === 'active' ? 'Request Preview' : 'Request Sent' }}
            </div>
            <div class="http-method">{{ activeStep.request.method }} {{ activeStep.request.url }}</div>
            <div class="http-headers">
              <div v-for="(v, k) in activeStep.request.headers" :key="k" class="header-line">
                <span class="header-key">{{ k }}:</span> {{ v }}
              </div>
            </div>
            <pre v-if="activeStep.request.body" class="http-body">{{ activeStep.request.body }}</pre>
          </div>

          <!-- No request (skipped before preview) -->
          <div v-if="!activeStep.request && activeStep.status === 'skipped'" class="detail-section warn-section">
            <div class="section-label"><i class="pi pi-info-circle"></i> Skipped</div>
            <p class="skip-reason">{{ activeStep.error }}</p>
          </div>

          <!-- Response -->
          <div v-if="activeStep.response" class="detail-section">
            <div class="section-label">
              Response
              <span
                class="status-badge"
                :class="activeStep.response.status < 300 ? 'status-ok' : 'status-err'"
              >
                {{ activeStep.response.status }} {{ activeStep.response.statusText }}
              </span>
            </div>
            <div class="http-headers">
              <div v-for="(v, k) in activeStep.response.headers" :key="k" class="header-line">
                <span class="header-key">{{ k }}:</span> {{ v }}
              </div>
            </div>
            <pre v-if="activeStep.response.body" class="http-body">{{ activeStep.response.body }}</pre>
            <div v-else class="empty-body">(empty body)</div>
          </div>

          <!-- Error detail -->
          <div v-if="activeStep.error && activeStep.status === 'fail'" class="detail-section error-section">
            <div class="section-label" style="color:#dc2626"><i class="pi pi-exclamation-triangle"></i> Error Detail</div>
            <pre class="error-body">{{ activeStep.error }}</pre>
          </div>

          <!-- Before / After diff -->
          <div v-if="activeStep.before !== undefined || activeStep.after !== undefined" class="detail-section">
            <div class="section-label">State Change</div>
            <div class="diff-panels">
              <div class="diff-pane">
                <div class="diff-label">Before</div>
                <pre class="diff-body">{{ activeStep.before ? JSON.stringify(activeStep.before, null, 2) : '(none)' }}</pre>
              </div>
              <div class="diff-pane">
                <div class="diff-label">After</div>
                <pre class="diff-body">{{ activeStep.after ? JSON.stringify(activeStep.after, null, 2) : '(deleted)' }}</pre>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- RIGHT: Map -->
      <div class="panel panel-map">
        <div class="panel-header">Map View</div>
        <div ref="mapContainer" class="map-container"></div>
        <div class="map-legend">
          <div v-for="(color, type) in TYPE_COLORS" :key="type" class="legend-item">
            <span class="legend-dot" :style="{ background: color }"></span>
            <span class="legend-label">{{ type }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.smoke-test {
  display: flex;
  flex-direction: column;
  height: calc(100vh - 56px);
  overflow: hidden;
}

/* ── Toolbar ──────────────────────── */
.smoke-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.5rem 1rem;
  border-bottom: 1px solid #e2e8f0;
  background: #f8fafc;
  flex-shrink: 0;
  flex-wrap: wrap;
  gap: 0.5rem;
}
.toolbar-left {
  display: flex;
  align-items: center;
  gap: 1rem;
}
.toolbar-left h2 {
  margin: 0;
  font-size: 1.1rem;
  display: flex;
  align-items: center;
  gap: 0.4rem;
}
.toolbar-right {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}
.action-slot {
  width: 150px;
  display: flex;
  justify-content: flex-end;
}
.action-slot-sm {
  width: 70px;
}
.action-slot-cleanup {
  width: 110px;
}
.btn-placeholder {
  display: block;
  width: 100%;
  height: 32px;
}
.toolbar-divider {
  width: 1px;
  height: 20px;
  background: #cbd5e1;
  margin: 0 0.25rem;
}
.progress-badge {
  font-size: 0.85rem;
  font-weight: 600;
}
.done-badge {
  display: inline-flex;
  align-items: center;
  gap: 0.3rem;
  color: #16a34a;
  font-weight: 700;
  font-size: 0.85rem;
}
.btn {
  display: inline-flex;
  align-items: center;
  gap: 0.3rem;
  padding: 0.4rem 0.9rem;
  border: none;
  border-radius: 6px;
  font-size: 0.85rem;
  font-weight: 600;
  cursor: pointer;
  transition: background 0.15s;
}
.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
.btn-primary { background: #3b82f6; color: #fff; }
.btn-primary:hover:not(:disabled) { background: #2563eb; }
.btn-execute { background: #16a34a; color: #fff; font-size: 0.9rem; padding: 0.45rem 1.1rem; }
.btn-execute:hover:not(:disabled) { background: #15803d; }
.btn-secondary { background: #e2e8f0; color: #334155; }
.btn-secondary:hover:not(:disabled) { background: #cbd5e1; }
.btn-danger { background: #dc2626; color: #fff; }
.btn-danger:hover:not(:disabled) { background: #b91c1c; }

/* ── Panels ───────────────────────── */
.panels {
  display: grid;
  grid-template-columns: 220px 1fr 1fr;
  flex: 1;
  overflow: hidden;
}
.panel {
  display: flex;
  flex-direction: column;
  border-right: 1px solid #e2e8f0;
  overflow: hidden;
}
.panel:last-child { border-right: none; }
.panel-header {
  padding: 0.5rem 0.75rem;
  font-weight: 700;
  font-size: 0.82rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: #64748b;
  border-bottom: 1px solid #e2e8f0;
  background: #f1f5f9;
  flex-shrink: 0;
}

/* ── Left: Plan ───────────────────── */
.plan-list {
  overflow-y: auto;
  flex: 1;
  padding: 0.25rem 0;
}
.plan-group {
  margin-bottom: 0.25rem;
}
.plan-group-label {
  padding: 0.4rem 0.75rem 0.2rem;
  font-size: 0.72rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: #94a3b8;
}
.plan-step {
  display: flex;
  align-items: center;
  gap: 0.4rem;
  padding: 0.35rem 0.75rem;
  font-size: 0.82rem;
  border-left: 3px solid transparent;
  transition: background 0.15s;
  opacity: 0.5;
}
.plan-step.clickable {
  cursor: pointer;
  opacity: 1;
}
.plan-step.clickable:hover { background: #f1f5f9; }
.plan-step.active {
  background: #eff6ff;
  border-left-color: #3b82f6;
  opacity: 1;
}
.step-time {
  margin-left: auto;
  font-size: 0.72rem;
  color: #94a3b8;
}

/* ── Op Badges ────────────────────── */
.op-badge {
  display: inline-block;
  padding: 0.1rem 0.4rem;
  border-radius: 4px;
  font-size: 0.68rem;
  font-weight: 700;
  letter-spacing: 0.04em;
}
.op-badge-lg {
  font-size: 0.82rem;
  padding: 0.2rem 0.6rem;
}
.op-create { background: #dcfce7; color: #15803d; }
.op-read { background: #dbeafe; color: #1d4ed8; }
.op-update { background: #fef3c7; color: #a16207; }
.op-verify { background: #e0e7ff; color: #4338ca; }
.op-delete { background: #fee2e2; color: #dc2626; }

/* ── Center: Detail ───────────────── */
.panel-detail {
  overflow: hidden;
  display: flex;
  flex-direction: column;
}
.panel-empty {
  display: flex;
  align-items: center;
  justify-content: center;
  flex: 1;
}
.empty-hero {
  text-align: center;
  color: #64748b;
}
.empty-hero p { margin: 0.5rem 0; font-size: 0.95rem; }
.empty-sub { font-size: 0.82rem; color: #94a3b8; }
.detail-content {
  overflow-y: auto;
  flex: 1;
  padding: 0.75rem;
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}
.step-header-card {
  display: flex;
  align-items: center;
  gap: 0.6rem;
  padding: 0.6rem 0.75rem;
  background: #f8fafc;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  flex-wrap: wrap;
}
.step-resource-label {
  font-weight: 700;
  font-size: 1rem;
}
.ready-indicator { color: #3b82f6; font-size: 0.82rem; }
.running-indicator { color: #3b82f6; font-size: 0.82rem; }
.success-indicator { color: #16a34a; font-size: 0.85rem; font-weight: 600; }
.fail-indicator { color: #dc2626; font-size: 0.85rem; font-weight: 600; }
.skip-indicator { color: #f59e0b; font-size: 0.85rem; font-weight: 600; }
.elapsed {
  font-size: 0.75rem;
  color: #94a3b8;
  margin-left: auto;
}
.detail-section {
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  padding: 0.6rem 0.75rem;
  background: #fff;
}
.section-label {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-weight: 700;
  font-size: 0.85rem;
  margin-bottom: 0.4rem;
}
.http-method {
  font-family: 'Consolas', 'Monaco', monospace;
  font-size: 0.85rem;
  font-weight: 700;
  color: #1e293b;
  padding: 0.3rem 0;
  border-bottom: 1px solid #f1f5f9;
  word-break: break-all;
}
.http-headers {
  font-family: 'Consolas', 'Monaco', monospace;
  font-size: 0.72rem;
  color: #64748b;
  padding: 0.25rem 0;
}
.header-line { line-height: 1.5; }
.header-key { color: #475569; font-weight: 600; }
.http-body {
  background: #f8fafc;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  padding: 0.5rem;
  font-size: 0.75rem;
  overflow-x: auto;
  max-height: 280px;
  overflow-y: auto;
  margin: 0.3rem 0 0;
  white-space: pre-wrap;
  word-break: break-word;
}
.empty-body {
  color: #94a3b8;
  font-style: italic;
  font-size: 0.82rem;
  padding: 0.3rem 0;
}
.status-badge {
  padding: 0.1rem 0.5rem;
  border-radius: 4px;
  font-size: 0.75rem;
  font-weight: 700;
}
.status-ok { background: #dcfce7; color: #15803d; }
.status-err { background: #fee2e2; color: #dc2626; }
.error-section {
  border-color: #fecaca;
  background: #fef2f2;
}
.error-body {
  font-size: 0.78rem;
  color: #dc2626;
  white-space: pre-wrap;
  word-break: break-word;
  margin: 0;
}
.warn-section {
  border-color: #fde68a;
  background: #fffbeb;
}
.skip-reason {
  margin: 0;
  font-size: 0.85rem;
  color: #a16207;
}

/* ── Diff panels ──────────────────── */
.diff-panels {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 0.5rem;
}
.diff-pane {
  overflow: hidden;
}
.diff-label {
  font-size: 0.72rem;
  font-weight: 700;
  text-transform: uppercase;
  color: #64748b;
  margin-bottom: 0.25rem;
}
.diff-body {
  background: #f8fafc;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  padding: 0.5rem;
  font-size: 0.72rem;
  overflow: auto;
  max-height: 200px;
  margin: 0;
  white-space: pre-wrap;
  word-break: break-word;
}

/* ── Right: Map ───────────────────── */
.panel-map {
  display: flex;
  flex-direction: column;
}
.map-container {
  flex: 1;
  min-height: 0;
}
.map-legend {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  padding: 0.4rem 0.75rem;
  background: #f8fafc;
  border-top: 1px solid #e2e8f0;
  flex-shrink: 0;
}
.legend-item {
  display: flex;
  align-items: center;
  gap: 0.25rem;
  font-size: 0.7rem;
  color: #64748b;
}
.legend-dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  flex-shrink: 0;
}

/* ── Responsive ───────────────────── */
@media (max-width: 1000px) {
  .panels {
    grid-template-columns: 180px 1fr;
    grid-template-rows: 1fr 300px;
  }
  .panel-plan { grid-row: 1 / 3; }
  .panel-map { border-right: none; border-top: 1px solid #e2e8f0; }
}
@media (max-width: 700px) {
  .panels {
    grid-template-columns: 1fr;
    grid-template-rows: 200px 1fr 250px;
  }
  .panel-plan { grid-row: auto; border-right: none; border-bottom: 1px solid #e2e8f0; }
}
</style>
