<script setup lang="ts">
import { ref, reactive, computed, onMounted, onUnmounted, watch, nextTick } from 'vue'
import { useRouter } from 'vue-router'
import { connection, RESOURCE_TYPES } from '../state'
import { apiFetch } from '../api'
import {
  getCreateUrl,
  getDetailUrl,
  getUpdateUrl,
  getDeleteUrl,
  getContentType,
  extractCSAPIFeature,
  getCSAPIResourceType,
} from '../csapi-bridge'

// OpenLayers
import OlMap from 'ol/Map'
import View from 'ol/View'
import TileLayer from 'ol/layer/Tile'
import VectorLayer from 'ol/layer/Vector'
import VectorSource from 'ol/source/Vector'
import OSM from 'ol/source/OSM'
import { fromLonLat, toLonLat } from 'ol/proj'
import OlFeature from 'ol/Feature'
import OlPoint from 'ol/geom/Point'
import { Style, Circle as CircleStyle, Fill, Stroke, Text as OlText, Icon } from 'ol/style'

const router = useRouter()

// Redirect if not connected
watch(
  () => connection.connected,
  (c) => { if (!c) router.push('/') },
  { immediate: true }
)

// ─── Types ───────────────────────────────────────────────

type OpType = 'CREATE' | 'READ' | 'UPDATE' | 'VERIFY' | 'DELETE'
type StepStatus = 'pending' | 'running' | 'success' | 'fail' | 'skipped'

interface Step {
  id: number
  resourceType: string
  resourceLabel: string
  op: OpType
  status: StepStatus
  /** populated after execution */
  request?: { method: string; url: string; headers: Record<string, string>; body?: string }
  response?: { status: number; statusText: string; headers: Record<string, string>; body: string }
  before?: any
  after?: any
  elapsed?: number
  error?: string
  /** coordinates for the map */
  coords?: [number, number]
}

// ─── Test Coordinates ────────────────────────────────────
// Using recognisable DC landmarks so the map movements are visible
const COORDS: Record<string, { create: [number, number]; update: [number, number] }> = {
  systems:           { create: [-77.0352, 38.8895], update: [-77.0502, 38.8893] }, // Washington Monument → Lincoln Memorial
  procedures:        { create: [-77.0366, 38.8977], update: [-77.0229, 38.8997] }, // White House → Capitol
  deployments:       { create: [-77.0098, 38.8899], update: [-77.0440, 38.8916] }, // Capitol Hill → Smithsonian
  samplingFeatures:  { create: [-77.0479, 38.8813], update: [-77.0365, 38.8822] }, // Tidal Basin → Jefferson Memorial
}

// ─── Test Payloads ───────────────────────────────────────

function makePayload(type: string, phase: 'create' | 'update', parentId?: string): any {
  const coords = COORDS[type]
  const c = coords ? coords[phase] : undefined
  const geom = c ? { type: 'Point', coordinates: c } : null

  const uid = `urn:csapi-explorer:smoke-test:${type}:${Date.now()}`
  const name = phase === 'create'
    ? `Smoke Test ${type}`
    : `Smoke Test ${type} (updated)`

  const featureTypes: Record<string, string> = {
    systems: 'http://www.w3.org/ns/sosa/Platform',
    procedures: 'http://www.w3.org/ns/sosa/Procedure',
    deployments: 'http://www.w3.org/ns/sosa/Deployment',
    samplingFeatures: 'http://www.w3.org/ns/sosa/Sample',
  }

  if (['systems', 'procedures', 'deployments', 'samplingFeatures'].includes(type)) {
    return {
      type: 'Feature',
      properties: {
        featureType: featureTypes[type],
        name,
        uid: phase === 'create' ? uid : undefined,
        description: `Auto-generated by CRUD smoke test (${phase})`,
      },
      geometry: geom,
    }
  }

  // Part 2 — datastreams (need parent system)
  if (type === 'datastreams') {
    return {
      name,
      outputName: 'smoke-test-output',
      schema: {
        obsFormat: 'application/json',
        recordSchema: {
          type: 'DataRecord',
          label: 'Smoke Test Record',
          fields: [
            { type: 'Quantity', label: 'Temperature', name: 'temp', uom: { code: 'Cel' } },
          ]
        }
      }
    }
  }

  if (type === 'observations') {
    return {
      phenomenonTime: new Date().toISOString(),
      resultTime: new Date().toISOString(),
      result: { temp: 22.5 },
    }
  }

  if (type === 'controlStreams') {
    return {
      name,
      inputName: 'smoke-test-input',
      schema: {
        cmdFormat: 'application/json',
        recordSchema: {
          type: 'DataRecord',
          label: 'Smoke Test Command',
          fields: [
            { type: 'Boolean', label: 'Active', name: 'active' },
          ]
        }
      }
    }
  }

  if (type === 'commands') {
    return {
      issueTime: new Date().toISOString(),
      params: { active: true },
    }
  }

  return { name }
}

// ─── Execution Order ─────────────────────────────────────
// Part 1 types first (they're standalone), then Part 2 (depend on parents).
// Delete in reverse order.

const PART1_TYPES = ['systems', 'procedures', 'deployments', 'samplingFeatures']
const PART2_TYPES = ['datastreams', 'observations', 'controlStreams', 'commands']
const CRUD_OPS: OpType[] = ['CREATE', 'READ', 'UPDATE', 'VERIFY', 'DELETE']

function buildSteps(): Step[] {
  const steps: Step[] = []
  let id = 1
  // Part 1
  for (const key of PART1_TYPES) {
    const info = RESOURCE_TYPES.find((r) => r.key === key)!
    for (const op of CRUD_OPS) {
      steps.push({ id: id++, resourceType: key, resourceLabel: info.label, op, status: 'pending' })
    }
  }
  // Part 2 — only if server might support them
  for (const key of PART2_TYPES) {
    const info = RESOURCE_TYPES.find((r) => r.key === key)!
    for (const op of CRUD_OPS) {
      steps.push({ id: id++, resourceType: key, resourceLabel: info.label, op, status: 'pending' })
    }
  }
  return steps
}

// ─── Reactive State ──────────────────────────────────────

const steps = ref<Step[]>(buildSteps())
const activeStepId = ref<number | null>(null)
const running = ref(false)
const autoRun = ref(false)
const testStarted = ref(false)

/** IDs of resources created, so we can reference them and clean up */
const createdIds = reactive<Record<string, string>>({})
/** Parent system ID for Part 2 nested resources */
const parentSystemId = ref<string>('')

const activeStep = computed(() => steps.value.find((s) => s.id === activeStepId.value) ?? null)

const completedCount = computed(() => steps.value.filter((s) => s.status === 'success' || s.status === 'fail' || s.status === 'skipped').length)
const successCount = computed(() => steps.value.filter((s) => s.status === 'success').length)
const failCount = computed(() => steps.value.filter((s) => s.status === 'fail').length)
const skippedCount = computed(() => steps.value.filter((s) => s.status === 'skipped').length)

// ─── Map ─────────────────────────────────────────────────

const mapContainer = ref<HTMLDivElement>()
let map: OlMap | null = null
const vectorSource = new VectorSource()

const TYPE_COLORS: Record<string, string> = {
  systems: '#3b82f6',
  procedures: '#f59e0b',
  deployments: '#8b5cf6',
  samplingFeatures: '#10b981',
  datastreams: '#ef4444',
  controlStreams: '#f97316',
  observations: '#06b6d4',
  commands: '#ec4899',
}

function markerStyle(resourceType: string, phase: 'create' | 'update' | 'ghost'): Style {
  const color = TYPE_COLORS[resourceType] || '#6b7280'
  const label = resourceType.charAt(0).toUpperCase()
  const isGhost = phase === 'ghost'
  return new Style({
    image: new CircleStyle({
      radius: isGhost ? 7 : 10,
      fill: new Fill({ color: isGhost ? 'transparent' : color }),
      stroke: new Stroke({ color, width: 2, lineDash: isGhost ? [4, 4] : undefined }),
    }),
    text: new OlText({
      text: isGhost ? '' : label,
      fill: new Fill({ color: '#fff' }),
      font: 'bold 11px sans-serif',
      offsetY: 1,
    }),
  })
}

function initMap() {
  if (!mapContainer.value || map) return
  map = new OlMap({
    target: mapContainer.value,
    layers: [
      new TileLayer({ source: new OSM() }),
      new VectorLayer({ source: vectorSource }),
    ],
    view: new View({
      center: fromLonLat([-77.035, 38.890]),
      zoom: 14,
    }),
  })
}

function addMarker(resourceType: string, coords: [number, number], featureId: string, phase: 'create' | 'update') {
  // Remove old marker for this resource
  const existing = vectorSource.getFeatureById(featureId)
  if (existing) vectorSource.removeFeature(existing)

  // If update, add a ghost at old position
  if (phase === 'update') {
    const oldCoords = COORDS[resourceType]?.create
    if (oldCoords) {
      const ghostId = featureId + '-ghost'
      const existingGhost = vectorSource.getFeatureById(ghostId)
      if (existingGhost) vectorSource.removeFeature(existingGhost)
      const ghost = new OlFeature({ geometry: new OlPoint(fromLonLat(oldCoords)) })
      ghost.setId(ghostId)
      ghost.setStyle(markerStyle(resourceType, 'ghost'))
      vectorSource.addFeature(ghost)
    }
  }

  const feature = new OlFeature({ geometry: new OlPoint(fromLonLat(coords)) })
  feature.setId(featureId)
  feature.setStyle(markerStyle(resourceType, phase))
  vectorSource.addFeature(feature)

  // Pan to
  map?.getView().animate({ center: fromLonLat(coords), duration: 500 })
}

function removeMarker(featureId: string) {
  const f = vectorSource.getFeatureById(featureId)
  if (f) vectorSource.removeFeature(f)
  const g = vectorSource.getFeatureById(featureId + '-ghost')
  if (g) vectorSource.removeFeature(g)
}

function clearMap() {
  vectorSource.clear()
}

// ─── Step Execution ──────────────────────────────────────

async function executeStep(step: Step) {
  step.status = 'running'
  activeStepId.value = step.id
  const start = performance.now()

  const contentType = getContentType(step.resourceType)
  const isPart1 = PART1_TYPES.includes(step.resourceType)

  try {
    switch (step.op) {
      case 'CREATE': {
        // Determine parent for nested Part 2 types
        let parentId: string | undefined
        if (step.resourceType === 'datastreams' || step.resourceType === 'controlStreams') {
          parentId = createdIds['systems']
          if (!parentId) {
            step.status = 'skipped'
            step.error = 'No parent system — skipping'
            step.elapsed = performance.now() - start
            return
          }
        }
        if (step.resourceType === 'observations') {
          parentId = createdIds['datastreams']
          if (!parentId) {
            step.status = 'skipped'
            step.error = 'No parent datastream — skipping'
            step.elapsed = performance.now() - start
            return
          }
        }
        if (step.resourceType === 'commands') {
          parentId = createdIds['controlStreams']
          if (!parentId) {
            step.status = 'skipped'
            step.error = 'No parent control stream — skipping'
            step.elapsed = performance.now() - start
            return
          }
        }

        const url = getCreateUrl(step.resourceType, parentId)
        const payload = makePayload(step.resourceType, 'create', parentId)
        const bodyStr = JSON.stringify(payload, null, 2)

        step.request = {
          method: 'POST',
          url,
          headers: { 'Content-Type': contentType, 'Accept': contentType },
          body: bodyStr,
        }
        step.before = null

        const resp = await apiFetch(url, {
          method: 'POST',
          headers: { 'Content-Type': contentType, 'Accept': contentType },
          body: bodyStr,
        })

        step.response = {
          status: resp.status,
          statusText: resp.statusText,
          headers: resp.headers,
          body: resp.data ? JSON.stringify(resp.data, null, 2) : '',
        }

        if (!resp.ok) {
          step.status = 'fail'
          step.error = resp.error || `${resp.status} ${resp.statusText}`
          step.elapsed = performance.now() - start
          return
        }

        // Extract ID from Location header
        const location = resp.headers['location'] || ''
        const id = location.split('/').pop() || ''
        if (id) createdIds[step.resourceType] = id

        step.after = resp.data || { id, location }
        step.status = 'success'

        // Map: add marker
        const coords = COORDS[step.resourceType]?.create
        if (coords && id) {
          step.coords = coords
          addMarker(step.resourceType, coords, `smoke-${step.resourceType}`, 'create')
        }
        break
      }

      case 'READ': {
        const id = createdIds[step.resourceType]
        if (!id) {
          step.status = 'skipped'
          step.error = 'No ID from CREATE — skipping'
          step.elapsed = performance.now() - start
          return
        }

        const url = getDetailUrl(step.resourceType, id)
        step.request = {
          method: 'GET',
          url,
          headers: { 'Accept': contentType },
        }

        const resp = await apiFetch(url, {
          method: 'GET',
          headers: { 'Accept': contentType },
        })

        step.response = {
          status: resp.status,
          statusText: resp.statusText,
          headers: resp.headers,
          body: resp.data ? JSON.stringify(resp.data, null, 2) : '',
        }

        if (!resp.ok) {
          step.status = 'fail'
          step.error = resp.error || `${resp.status} ${resp.statusText}`
        } else {
          step.before = resp.data
          step.after = resp.data
          step.status = 'success'

          // Map: pulse marker (re-add to trigger visual)
          const coords = COORDS[step.resourceType]?.create
          if (coords) {
            step.coords = coords
          }
        }
        break
      }

      case 'UPDATE': {
        const id = createdIds[step.resourceType]
        if (!id) {
          step.status = 'skipped'
          step.error = 'No ID from CREATE — skipping'
          step.elapsed = performance.now() - start
          return
        }

        // Get current state as "before"
        const readUrl = getDetailUrl(step.resourceType, id)
        const readResp = await apiFetch(readUrl, {
          method: 'GET',
          headers: { 'Accept': contentType },
        })
        step.before = readResp.data

        const url = getUpdateUrl(step.resourceType, id)
        const payload = makePayload(step.resourceType, 'update')
        const bodyStr = JSON.stringify(payload, null, 2)

        step.request = {
          method: 'PUT',
          url,
          headers: { 'Content-Type': contentType, 'Accept': contentType },
          body: bodyStr,
        }

        const resp = await apiFetch(url, {
          method: 'PUT',
          headers: { 'Content-Type': contentType, 'Accept': contentType },
          body: bodyStr,
        })

        step.response = {
          status: resp.status,
          statusText: resp.statusText,
          headers: resp.headers,
          body: resp.data ? JSON.stringify(resp.data, null, 2) : '',
        }

        if (!resp.ok) {
          step.status = 'fail'
          step.error = resp.error || `${resp.status} ${resp.statusText}`
        } else {
          step.after = resp.data || payload
          step.status = 'success'

          // Map: move marker
          const coords = COORDS[step.resourceType]?.update
          if (coords) {
            step.coords = coords
            addMarker(step.resourceType, coords, `smoke-${step.resourceType}`, 'update')
          }
        }
        break
      }

      case 'VERIFY': {
        const id = createdIds[step.resourceType]
        if (!id) {
          step.status = 'skipped'
          step.error = 'No ID from CREATE — skipping'
          step.elapsed = performance.now() - start
          return
        }

        const url = getDetailUrl(step.resourceType, id)
        step.request = {
          method: 'GET',
          url,
          headers: { 'Accept': contentType },
        }

        const resp = await apiFetch(url, {
          method: 'GET',
          headers: { 'Accept': contentType },
        })

        step.response = {
          status: resp.status,
          statusText: resp.statusText,
          headers: resp.headers,
          body: resp.data ? JSON.stringify(resp.data, null, 2) : '',
        }

        if (!resp.ok) {
          step.status = 'fail'
          step.error = resp.error || `${resp.status} ${resp.statusText}`
        } else {
          // "before" = what we sent in UPDATE, "after" = what server has now
          const updateStep = steps.value.find(
            (s) => s.resourceType === step.resourceType && s.op === 'UPDATE'
          )
          step.before = updateStep?.after || null
          step.after = resp.data
          step.status = 'success'
        }
        break
      }

      case 'DELETE': {
        const id = createdIds[step.resourceType]
        if (!id) {
          step.status = 'skipped'
          step.error = 'No ID from CREATE — skipping'
          step.elapsed = performance.now() - start
          return
        }

        // Get current state as "before"
        const readUrl = getDetailUrl(step.resourceType, id)
        const readResp = await apiFetch(readUrl, {
          method: 'GET',
          headers: { 'Accept': contentType },
        })
        step.before = readResp.data

        const url = getDeleteUrl(step.resourceType, id)
        step.request = {
          method: 'DELETE',
          url,
          headers: {},
        }

        const resp = await apiFetch(url, { method: 'DELETE' })

        step.response = {
          status: resp.status,
          statusText: resp.statusText,
          headers: resp.headers,
          body: '',
        }

        if (!resp.ok) {
          step.status = 'fail'
          step.error = resp.error || `${resp.status} ${resp.statusText}`
        } else {
          step.after = null
          step.status = 'success'
          delete createdIds[step.resourceType]

          // Map: remove marker
          removeMarker(`smoke-${step.resourceType}`)
        }
        break
      }
    }
  } catch (err: any) {
    step.status = 'fail'
    step.error = err.message || 'Unknown error'
  }

  step.elapsed = performance.now() - start
}

// ─── Controls ────────────────────────────────────────────

async function runNextStep() {
  const next = steps.value.find((s) => s.status === 'pending')
  if (!next) return
  testStarted.value = true
  running.value = true
  await executeStep(next)
  running.value = false

  if (autoRun.value) {
    const hasMore = steps.value.some((s) => s.status === 'pending')
    if (hasMore) {
      await new Promise((r) => setTimeout(r, 300))
      runNextStep()
    } else {
      autoRun.value = false
    }
  }
}

async function runAll() {
  testStarted.value = true
  autoRun.value = true
  running.value = true
  await runNextStep()
}

function stopAutoRun() {
  autoRun.value = false
}

async function abortAndCleanup() {
  autoRun.value = false
  running.value = true

  // Delete in reverse order: commands, controlStreams, observations, datastreams, then Part 1
  const deleteOrder = ['commands', 'controlStreams', 'observations', 'datastreams', 'samplingFeatures', 'deployments', 'procedures', 'systems']
  for (const type of deleteOrder) {
    const id = createdIds[type]
    if (!id) continue
    try {
      const url = getDeleteUrl(type, id)
      await apiFetch(url, { method: 'DELETE' })
      delete createdIds[type]
      removeMarker(`smoke-${type}`)
    } catch { /* best effort */ }
  }

  running.value = false
}

function resetTest() {
  steps.value = buildSteps()
  activeStepId.value = null
  testStarted.value = false
  autoRun.value = false
  running.value = false
  for (const key of Object.keys(createdIds)) delete createdIds[key]
  clearMap()
}

function selectStep(step: Step) {
  activeStepId.value = step.id
  // Pan map if step has coords
  if (step.coords && map) {
    map.getView().animate({ center: fromLonLat(step.coords), duration: 400 })
  }
}

// ─── Formatting helpers ──────────────────────────────────

function opBadgeClass(op: OpType): string {
  return {
    CREATE: 'op-create',
    READ: 'op-read',
    UPDATE: 'op-update',
    VERIFY: 'op-verify',
    DELETE: 'op-delete',
  }[op]
}

function statusIcon(status: StepStatus): string {
  return {
    pending: 'pi pi-circle',
    running: 'pi pi-spin pi-spinner',
    success: 'pi pi-check-circle',
    fail: 'pi pi-times-circle',
    skipped: 'pi pi-minus-circle',
  }[status]
}

function statusColor(status: StepStatus): string {
  return {
    pending: '#94a3b8',
    running: '#3b82f6',
    success: '#16a34a',
    fail: '#dc2626',
    skipped: '#f59e0b',
  }[status]
}

function formatMs(ms?: number): string {
  if (ms == null) return ''
  return ms < 1000 ? `${Math.round(ms)}ms` : `${(ms / 1000).toFixed(1)}s`
}

// Group steps by resource type for the left panel
const groupedSteps = computed(() => {
  const groups: { type: string; label: string; steps: Step[] }[] = []
  let current: (typeof groups)[0] | null = null
  for (const step of steps.value) {
    if (!current || current.type !== step.resourceType) {
      current = { type: step.resourceType, label: step.resourceLabel, steps: [] }
      groups.push(current)
    }
    current.steps.push(step)
  }
  return groups
})

// ─── Lifecycle ───────────────────────────────────────────

onMounted(() => {
  nextTick(() => initMap())
})

onUnmounted(() => {
  map?.setTarget(undefined)
  map = null
})
</script>

<template>
  <div class="smoke-test">
    <!-- Top bar -->
    <div class="smoke-toolbar">
      <div class="toolbar-left">
        <h2><i class="pi pi-bolt"></i> CRUD Smoke Test</h2>
        <span v-if="testStarted" class="progress-badge">
          {{ completedCount }}/{{ steps.length }} —
          <span style="color:#16a34a">{{ successCount }} pass</span>
          <span v-if="failCount" style="color:#dc2626"> · {{ failCount }} fail</span>
          <span v-if="skippedCount" style="color:#f59e0b"> · {{ skippedCount }} skip</span>
        </span>
      </div>
      <div class="toolbar-right">
        <button v-if="!testStarted" class="btn btn-primary" @click="runAll" :disabled="running">
          <i class="pi pi-play"></i> Run All
        </button>
        <button v-if="!autoRun && testStarted" class="btn btn-primary" @click="runNextStep"
          :disabled="running || !steps.some(s => s.status === 'pending')">
          <i class="pi pi-step-forward"></i> Next Step
        </button>
        <button v-if="!autoRun && testStarted" class="btn btn-secondary" @click="runAll"
          :disabled="running || !steps.some(s => s.status === 'pending')">
          <i class="pi pi-forward"></i> Run Remaining
        </button>
        <button v-if="autoRun" class="btn btn-warning" @click="stopAutoRun">
          <i class="pi pi-pause"></i> Pause
        </button>
        <button v-if="testStarted" class="btn btn-danger" @click="abortAndCleanup" :disabled="running && !autoRun">
          <i class="pi pi-trash"></i> Abort &amp; Cleanup
        </button>
        <button class="btn btn-secondary" @click="resetTest" :disabled="running">
          <i class="pi pi-refresh"></i> Reset
        </button>
      </div>
    </div>

    <!-- Tri-panel -->
    <div class="panels">
      <!-- LEFT: Test Plan -->
      <div class="panel panel-plan">
        <div class="panel-header">Test Plan</div>
        <div class="plan-list">
          <div v-for="group in groupedSteps" :key="group.type" class="plan-group">
            <div class="plan-group-label">{{ group.label }}</div>
            <div
              v-for="step in group.steps"
              :key="step.id"
              class="plan-step"
              :class="{ active: step.id === activeStepId }"
              @click="selectStep(step)"
            >
              <i :class="statusIcon(step.status)" :style="{ color: statusColor(step.status) }"></i>
              <span class="op-badge" :class="opBadgeClass(step.op)">{{ step.op }}</span>
              <span v-if="step.elapsed" class="step-time">{{ formatMs(step.elapsed) }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- CENTER: Request / Response -->
      <div class="panel panel-detail">
        <div class="panel-header">Request / Response</div>
        <div v-if="!activeStep" class="panel-empty">
          <p>Select a step or click <b>Run All</b> to begin.</p>
        </div>
        <div v-else class="detail-content">
          <!-- Request -->
          <div class="detail-section">
            <div class="section-label">
              <span class="op-badge" :class="opBadgeClass(activeStep.op)">{{ activeStep.op }}</span>
              {{ activeStep.resourceLabel }}
              <span v-if="activeStep.status === 'running'" class="running-indicator">
                <i class="pi pi-spin pi-spinner"></i> Executing...
              </span>
            </div>
            <div v-if="activeStep.request" class="http-block">
              <div class="http-method">{{ activeStep.request.method }} {{ activeStep.request.url }}</div>
              <div class="http-headers">
                <div v-for="(v, k) in activeStep.request.headers" :key="k" class="header-line">
                  <span class="header-key">{{ k }}:</span> {{ v }}
                </div>
              </div>
              <pre v-if="activeStep.request.body" class="http-body">{{ activeStep.request.body }}</pre>
            </div>
            <div v-else-if="activeStep.status === 'pending'" class="pending-msg">
              Awaiting execution...
            </div>
          </div>

          <!-- Response -->
          <div v-if="activeStep.response" class="detail-section">
            <div class="section-label">
              Response
              <span
                class="status-badge"
                :class="activeStep.response.status < 300 ? 'status-ok' : 'status-err'"
              >
                {{ activeStep.response.status }} {{ activeStep.response.statusText }}
              </span>
              <span v-if="activeStep.elapsed" class="elapsed">{{ formatMs(activeStep.elapsed) }}</span>
            </div>
            <div class="http-headers">
              <div v-for="(v, k) in activeStep.response.headers" :key="k" class="header-line">
                <span class="header-key">{{ k }}:</span> {{ v }}
              </div>
            </div>
            <pre v-if="activeStep.response.body" class="http-body">{{ activeStep.response.body }}</pre>
            <div v-else class="empty-body">(empty body)</div>
          </div>

          <!-- Error -->
          <div v-if="activeStep.error" class="detail-section error-section">
            <div class="section-label" style="color:#dc2626"><i class="pi pi-exclamation-triangle"></i> Error</div>
            <pre class="error-body">{{ activeStep.error }}</pre>
          </div>

          <!-- Before / After diff -->
          <div v-if="activeStep.before !== undefined || activeStep.after !== undefined" class="detail-section">
            <div class="section-label">State Diff</div>
            <div class="diff-panels">
              <div class="diff-pane">
                <div class="diff-label">Before</div>
                <pre class="diff-body">{{ activeStep.before ? JSON.stringify(activeStep.before, null, 2) : '(none)' }}</pre>
              </div>
              <div class="diff-pane">
                <div class="diff-label">After</div>
                <pre class="diff-body">{{ activeStep.after ? JSON.stringify(activeStep.after, null, 2) : '(deleted)' }}</pre>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- RIGHT: Map -->
      <div class="panel panel-map">
        <div class="panel-header">Map View</div>
        <div ref="mapContainer" class="map-container"></div>
        <div class="map-legend">
          <div v-for="(color, type) in TYPE_COLORS" :key="type" class="legend-item">
            <span class="legend-dot" :style="{ background: color }"></span>
            <span class="legend-label">{{ type }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.smoke-test {
  display: flex;
  flex-direction: column;
  height: calc(100vh - 56px);
  overflow: hidden;
}

/* ── Toolbar ──────────────────────── */
.smoke-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.5rem 1rem;
  border-bottom: 1px solid #e2e8f0;
  background: #f8fafc;
  flex-shrink: 0;
}
.toolbar-left {
  display: flex;
  align-items: center;
  gap: 1rem;
}
.toolbar-left h2 {
  margin: 0;
  font-size: 1.1rem;
  display: flex;
  align-items: center;
  gap: 0.4rem;
}
.toolbar-right {
  display: flex;
  gap: 0.5rem;
}
.progress-badge {
  font-size: 0.85rem;
  font-weight: 600;
}
.btn {
  display: inline-flex;
  align-items: center;
  gap: 0.3rem;
  padding: 0.35rem 0.8rem;
  border: none;
  border-radius: 6px;
  font-size: 0.82rem;
  font-weight: 600;
  cursor: pointer;
}
.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
.btn-primary { background: #3b82f6; color: #fff; }
.btn-primary:hover:not(:disabled) { background: #2563eb; }
.btn-secondary { background: #e2e8f0; color: #334155; }
.btn-secondary:hover:not(:disabled) { background: #cbd5e1; }
.btn-warning { background: #f59e0b; color: #fff; }
.btn-warning:hover:not(:disabled) { background: #d97706; }
.btn-danger { background: #dc2626; color: #fff; }
.btn-danger:hover:not(:disabled) { background: #b91c1c; }

/* ── Panels ───────────────────────── */
.panels {
  display: grid;
  grid-template-columns: 220px 1fr 1fr;
  flex: 1;
  overflow: hidden;
}
.panel {
  display: flex;
  flex-direction: column;
  border-right: 1px solid #e2e8f0;
  overflow: hidden;
}
.panel:last-child { border-right: none; }
.panel-header {
  padding: 0.5rem 0.75rem;
  font-weight: 700;
  font-size: 0.82rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: #64748b;
  border-bottom: 1px solid #e2e8f0;
  background: #f1f5f9;
  flex-shrink: 0;
}

/* ── Left: Plan ───────────────────── */
.plan-list {
  overflow-y: auto;
  flex: 1;
  padding: 0.25rem 0;
}
.plan-group {
  margin-bottom: 0.25rem;
}
.plan-group-label {
  padding: 0.35rem 0.75rem 0.15rem;
  font-size: 0.72rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: #94a3b8;
}
.plan-step {
  display: flex;
  align-items: center;
  gap: 0.4rem;
  padding: 0.3rem 0.75rem;
  cursor: pointer;
  font-size: 0.82rem;
  border-left: 3px solid transparent;
  transition: background 0.15s;
}
.plan-step:hover { background: #f1f5f9; }
.plan-step.active {
  background: #eff6ff;
  border-left-color: #3b82f6;
}
.step-time {
  margin-left: auto;
  font-size: 0.72rem;
  color: #94a3b8;
}

/* ── Op Badges ────────────────────── */
.op-badge {
  display: inline-block;
  padding: 0.1rem 0.4rem;
  border-radius: 4px;
  font-size: 0.68rem;
  font-weight: 700;
  letter-spacing: 0.04em;
}
.op-create { background: #dcfce7; color: #15803d; }
.op-read { background: #dbeafe; color: #1d4ed8; }
.op-update { background: #fef3c7; color: #a16207; }
.op-verify { background: #e0e7ff; color: #4338ca; }
.op-delete { background: #fee2e2; color: #dc2626; }

/* ── Center: Detail ───────────────── */
.panel-detail {
  overflow: hidden;
  display: flex;
  flex-direction: column;
}
.panel-empty {
  display: flex;
  align-items: center;
  justify-content: center;
  flex: 1;
  color: #94a3b8;
  font-size: 0.9rem;
}
.detail-content {
  overflow-y: auto;
  flex: 1;
  padding: 0.75rem;
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}
.detail-section {
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  padding: 0.6rem 0.75rem;
  background: #fff;
}
.section-label {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-weight: 700;
  font-size: 0.85rem;
  margin-bottom: 0.4rem;
}
.running-indicator {
  color: #3b82f6;
  font-weight: 400;
  font-size: 0.82rem;
}
.http-method {
  font-family: 'Consolas', 'Monaco', monospace;
  font-size: 0.82rem;
  font-weight: 700;
  color: #1e293b;
  padding: 0.3rem 0;
  border-bottom: 1px solid #f1f5f9;
  word-break: break-all;
}
.http-headers {
  font-family: 'Consolas', 'Monaco', monospace;
  font-size: 0.72rem;
  color: #64748b;
  padding: 0.25rem 0;
}
.header-line { line-height: 1.5; }
.header-key { color: #475569; font-weight: 600; }
.http-body {
  background: #f8fafc;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  padding: 0.5rem;
  font-size: 0.75rem;
  overflow-x: auto;
  max-height: 250px;
  overflow-y: auto;
  margin: 0.3rem 0 0;
  white-space: pre-wrap;
  word-break: break-word;
}
.empty-body {
  color: #94a3b8;
  font-style: italic;
  font-size: 0.82rem;
  padding: 0.3rem 0;
}
.pending-msg {
  color: #94a3b8;
  font-style: italic;
  font-size: 0.85rem;
  padding: 0.5rem 0;
}
.status-badge {
  padding: 0.1rem 0.5rem;
  border-radius: 4px;
  font-size: 0.75rem;
  font-weight: 700;
}
.status-ok { background: #dcfce7; color: #15803d; }
.status-err { background: #fee2e2; color: #dc2626; }
.elapsed {
  font-size: 0.75rem;
  color: #94a3b8;
  margin-left: auto;
}
.error-section {
  border-color: #fecaca;
  background: #fef2f2;
}
.error-body {
  font-size: 0.78rem;
  color: #dc2626;
  white-space: pre-wrap;
  word-break: break-word;
  margin: 0;
}

/* ── Diff panels ──────────────────── */
.diff-panels {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 0.5rem;
}
.diff-pane {
  overflow: hidden;
}
.diff-label {
  font-size: 0.72rem;
  font-weight: 700;
  text-transform: uppercase;
  color: #64748b;
  margin-bottom: 0.25rem;
}
.diff-body {
  background: #f8fafc;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  padding: 0.5rem;
  font-size: 0.72rem;
  overflow: auto;
  max-height: 200px;
  margin: 0;
  white-space: pre-wrap;
  word-break: break-word;
}

/* ── Right: Map ───────────────────── */
.panel-map {
  display: flex;
  flex-direction: column;
}
.map-container {
  flex: 1;
  min-height: 0;
}
.map-legend {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  padding: 0.4rem 0.75rem;
  background: #f8fafc;
  border-top: 1px solid #e2e8f0;
  flex-shrink: 0;
}
.legend-item {
  display: flex;
  align-items: center;
  gap: 0.25rem;
  font-size: 0.7rem;
  color: #64748b;
}
.legend-dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  flex-shrink: 0;
}

/* ── Responsive ───────────────────── */
@media (max-width: 1000px) {
  .panels {
    grid-template-columns: 180px 1fr;
    grid-template-rows: 1fr 300px;
  }
  .panel-plan {
    grid-row: 1 / 3;
  }
  .panel-map {
    border-right: none;
    border-top: 1px solid #e2e8f0;
  }
}
@media (max-width: 700px) {
  .panels {
    grid-template-columns: 1fr;
    grid-template-rows: 200px 1fr 250px;
  }
  .panel-plan {
    grid-row: auto;
    border-right: none;
    border-bottom: 1px solid #e2e8f0;
  }
}
</style>
