<script setup lang="ts">
import { ref, reactive, computed, onMounted, onUnmounted, watch, nextTick } from 'vue'
import { useRouter } from 'vue-router'
import { connection, RESOURCE_TYPES } from '../state'
import { apiFetch } from '../api'
import {
  getCreateUrl,
  getDetailUrl,
  getUpdateUrl,
  getDeleteUrl,
  getContentType,
  extractCSAPIFeature,
  getCSAPIResourceType,
} from '../csapi-bridge'

// OpenLayers
import OlMap from 'ol/Map'
import View from 'ol/View'
import TileLayer from 'ol/layer/Tile'
import VectorLayer from 'ol/layer/Vector'
import VectorSource from 'ol/source/Vector'
import OSM from 'ol/source/OSM'
import { fromLonLat } from 'ol/proj'
import OlFeature from 'ol/Feature'
import OlPoint from 'ol/geom/Point'
import { Style, Circle as CircleStyle, Fill, Stroke, Text as OlText } from 'ol/style'

const router = useRouter()

watch(
  () => connection.connected,
  (c) => { if (!c) router.push('/') },
  { immediate: true }
)

// ─── Types ───────────────────────────────────────────────

type OpType = 'CREATE' | 'READ' | 'UPDATE' | 'VERIFY' | 'DELETE'
type StepStatus = 'pending' | 'active' | 'running' | 'success' | 'fail' | 'skipped'

interface Step {
  id: number
  resourceType: string
  resourceLabel: string
  op: OpType
  status: StepStatus
  request?: { method: string; url: string; headers: Record<string, string>; body?: string }
  response?: { status: number; statusText: string; headers: Record<string, string>; body: string; rawError?: string }
  before?: any
  after?: any
  elapsed?: number
  error?: string
  coords?: [number, number]
}

// ─── Test Coordinates ────────────────────────────────────
const COORDS: Record<string, { create: [number, number]; update: [number, number] }> = {
  systems:           { create: [-77.0352, 38.8895], update: [-77.0502, 38.8893] },
  procedures:        { create: [-77.0366, 38.8977], update: [-77.0229, 38.8997] },
  deployments:       { create: [-77.0098, 38.8899], update: [-77.0440, 38.8916] },
  samplingFeatures:  { create: [-77.0479, 38.8813], update: [-77.0365, 38.8822] },
  observations:      { create: [-77.0560, 38.8710], update: [-77.0420, 38.8780] },
  subsystems:        { create: [-77.0280, 38.8850], update: [-77.0320, 38.8860] },
  subdeployments:    { create: [-77.0150, 38.8940], update: [-77.0200, 38.8950] },
}

// ─── Test Payloads ───────────────────────────────────────

/** Unique keyword embedded in all smoke-test resources so they can be found
 *  via the Explorer page's free-text search (q filter).  Search for this
 *  exact string to see only smoke-test leftovers. */
const SMOKE_TAG = 'csapi-smoke-test-resource'

function makePayload(type: string, phase: 'create' | 'update'): any {
  const coords = COORDS[type]
  const c = coords ? coords[phase] : undefined
  const geom = c ? { type: 'Point', coordinates: c } : null

  const uid = phase === 'create'
    ? `urn:csapi-explorer:smoke-test:${type}:${Date.now()}`
    : createdUids[type]  // Reuse original UID on update — OSH requires it
  const name = phase === 'create'
    ? `[${SMOKE_TAG}] Smoke Test ${type}`
    : `[${SMOKE_TAG}] Smoke Test ${type} (updated)`

  const featureTypes: Record<string, string> = {
    systems: 'http://www.w3.org/ns/sosa/Platform',
    procedures: 'http://www.w3.org/ns/sosa/Procedure',
    deployments: 'http://www.w3.org/ns/sosa/Deployment',
    samplingFeatures: 'http://www.w3.org/ns/sosa/Sample',
  }

  if (['systems', 'procedures', 'deployments', 'samplingFeatures'].includes(type)) {
    return {
      type: 'Feature',
      properties: {
        featureType: featureTypes[type],
        name,
        uid,
        description: `Auto-generated by CRUD smoke test (${phase}). Tag: ${SMOKE_TAG}`,
      },
      geometry: geom,
    }
  }

  // Subsystems are systems created under a parent system
  if (type === 'subsystems') {
    return {
      type: 'Feature',
      properties: {
        featureType: 'http://www.w3.org/ns/sosa/Sensor',
        name: phase === 'create'
          ? `[${SMOKE_TAG}] Smoke Test Subsystem`
          : `[${SMOKE_TAG}] Smoke Test Subsystem (updated)`,
        uid: phase === 'create'
          ? `urn:csapi-explorer:smoke-test:subsystem:${Date.now()}`
          : createdUids['subsystems'],
        description: `Subsystem sensor created under parent system. Tag: ${SMOKE_TAG}`,
      },
      geometry: geom,
    }
  }

  // Subdeployments are deployments created under a parent deployment
  if (type === 'subdeployments') {
    return {
      type: 'Feature',
      properties: {
        featureType: 'http://www.w3.org/ns/sosa/Deployment',
        name: phase === 'create'
          ? `[${SMOKE_TAG}] Smoke Test Subdeployment`
          : `[${SMOKE_TAG}] Smoke Test Subdeployment (updated)`,
        uid: phase === 'create'
          ? `urn:csapi-explorer:smoke-test:subdeployment:${Date.now()}`
          : createdUids['subdeployments'],
        description: `Subdeployment created under parent deployment. Tag: ${SMOKE_TAG}`,
      },
      geometry: geom,
    }
  }

  if (type === 'datastreams') {
    return {
      name,
      outputName: 'smoke-test-output',
      schema: {
        obsFormat: 'application/swe+json',
        recordSchema: {
          type: 'DataRecord',
          label: 'Smoke Test Record',
          fields: [
            { type: 'Time', label: 'Timestamp', name: 'timestamp', definition: 'http://www.opengis.net/def/property/OGC/0/SamplingTime', uom: { href: 'http://www.opengis.net/def/uom/ISO-8601/0/Gregorian' } },
            { type: 'Quantity', label: 'Temperature', name: 'temp', uom: { code: 'Cel' } },
            { type: 'DataRecord', label: 'Location', name: 'location', fields: [
              { type: 'Quantity', label: 'Latitude', name: 'lat', uom: { code: 'deg' } },
              { type: 'Quantity', label: 'Longitude', name: 'lon', uom: { code: 'deg' } },
            ]},
          ]
        }
      }
    }
  }

  if (type === 'observations') {
    const obsCoords = COORDS['observations']?.[phase]
    return {
      phenomenonTime: new Date().toISOString(),
      resultTime: new Date().toISOString(),
      result: {
        temp: phase === 'create' ? 22.5 : 25.0,
        location: obsCoords ? { lat: obsCoords[1], lon: obsCoords[0] } : undefined,
      },
    }
  }

  if (type === 'controlStreams') {
    // CREATE: include full schema; UPDATE: omit schema — OSH returns 500 on
    // PUT when the schema block is present (server bug in control stream update handler)
    if (phase === 'create') {
      return {
        name,
        inputName: 'smoke-test-input',
        schema: {
          paramsSchema: {
            type: 'DataRecord',
            label: 'Smoke Test Command',
            fields: [
              { type: 'Time', label: 'Timestamp', name: 'timestamp', definition: 'http://www.opengis.net/def/property/OGC/0/SamplingTime', uom: { href: 'http://www.opengis.net/def/uom/ISO-8601/0/Gregorian' } },
              { type: 'Boolean', label: 'Active', name: 'active' },
            ]
          }
        }
      }
    }
    return {
      name,
      inputName: 'smoke-test-input',
    }
  }

  if (type === 'commands') {
    return {
      issueTime: new Date().toISOString(),
      parameters: { active: phase === 'create' },
    }
  }

  return { name }
}

// ─── Step Building ───────────────────────────────────────

const PART1_TYPES = ['systems', 'procedures', 'deployments', 'samplingFeatures']
const NESTED_HIERARCHY_TYPES = ['subsystems', 'subdeployments']  // Nested under Part 1 parents
const PART2_PARENT_TYPES = ['datastreams', 'controlStreams']   // Need parent system alive
const PART2_CHILD_TYPES_CRD = ['observations']                    // Immutable but persisted — CREATE/READ/DELETE
const PART2_CHILD_TYPES_CREATE_ONLY = ['commands']                 // Async dispatch (202) — CREATE only, no persisted resource
const CRUV_OPS: OpType[] = ['CREATE', 'READ', 'UPDATE', 'VERIFY']  // No DELETE — children need parents alive
const CRUD_OPS: OpType[] = ['CREATE', 'READ', 'UPDATE', 'VERIFY', 'DELETE']
const CRD_OPS: OpType[] = ['CREATE', 'READ', 'DELETE']  // Observations — immutable, no UPDATE
const CREATE_ONLY_OPS: OpType[] = ['CREATE']  // Commands — async dispatch, 202 with no persisted ID

/** Maps virtual nested types to their actual resource type (for content-type, detail/update/delete URLs) */
const NESTED_ACTUAL_TYPE: Record<string, string> = {
  subsystems: 'systems',
  subdeployments: 'deployments',
}

/** Maps virtual nested types to the parent type they nest under */
const NESTED_PARENT_TYPE: Record<string, string> = {
  subsystems: 'systems',
  subdeployments: 'deployments',
}

/** Human-readable labels for virtual nested types */
const NESTED_LABELS: Record<string, string> = {
  subsystems: 'Subsystem',
  subdeployments: 'Subdeployment',
}

function buildSteps(): Step[] {
  const steps: Step[] = []
  let id = 1
  // Phase 1: Part 1 CRUV (keep Part 1 resources alive for Part 2 parents)
  for (const key of PART1_TYPES) {
    const info = RESOURCE_TYPES.find((r) => r.key === key)!
    for (const op of CRUV_OPS) {
      steps.push({ id: id++, resourceType: key, resourceLabel: info.label, op, status: 'pending' })
    }
  }
  // Phase 1b: Nested hierarchy CRUV (subsystems under systems, subdeployments under deployments)
  for (const key of NESTED_HIERARCHY_TYPES) {
    const label = NESTED_LABELS[key]
    for (const op of CRUV_OPS) {
      steps.push({ id: id++, resourceType: key, resourceLabel: label, op, status: 'pending' })
    }
  }
  // Phase 1c: Nested hierarchy DELETE (before parents are deleted)
  for (const key of NESTED_HIERARCHY_TYPES) {
    const label = NESTED_LABELS[key]
    steps.push({ id: id++, resourceType: key, resourceLabel: label, op: 'DELETE', status: 'pending' })
  }
  // Phase 2a: Part 2 parent CRUV (keep datastreams/controlStreams alive for observations/commands)
  for (const key of PART2_PARENT_TYPES) {
    const info = RESOURCE_TYPES.find((r) => r.key === key)!
    for (const op of CRUV_OPS) {
      steps.push({ id: id++, resourceType: key, resourceLabel: info.label, op, status: 'pending' })
    }
  }
  // Phase 2b: Part 2 child CRD (observations — immutable, no UPDATE)
  for (const key of PART2_CHILD_TYPES_CRD) {
    const info = RESOURCE_TYPES.find((r) => r.key === key)!
    for (const op of CRD_OPS) {
      steps.push({ id: id++, resourceType: key, resourceLabel: info.label, op, status: 'pending' })
    }
  }
  // Phase 2b-2: Commands — async dispatch only (OSH returns 202, no persisted resource)
  for (const key of PART2_CHILD_TYPES_CREATE_ONLY) {
    const info = RESOURCE_TYPES.find((r) => r.key === key)!
    for (const op of CREATE_ONLY_OPS) {
      steps.push({ id: id++, resourceType: key, resourceLabel: info.label, op, status: 'pending' })
    }
  }
  // Phase 2c: Part 2 parent DELETE (cleanup datastreams/controlStreams after children are done)
  for (const key of PART2_PARENT_TYPES) {
    const info = RESOURCE_TYPES.find((r) => r.key === key)!
    steps.push({ id: id++, resourceType: key, resourceLabel: info.label, op: 'DELETE', status: 'pending' })
  }
  // Phase 3: Part 1 DELETE (cleanup systems, procedures, etc.)
  for (const key of PART1_TYPES) {
    const info = RESOURCE_TYPES.find((r) => r.key === key)!
    steps.push({ id: id++, resourceType: key, resourceLabel: info.label, op: 'DELETE', status: 'pending' })
  }
  return steps
}

// ─── Reactive State ──────────────────────────────────────

const steps = ref<Step[]>(buildSteps())
const currentStepIndex = ref(-1)
const running = ref(false)
const testStarted = ref(false)
const cleanupMessage = ref('')
const showReport = ref(false)

const createdIds = reactive<Record<string, string>>({})
const createdUids = reactive<Record<string, string>>({})

const activeStep = computed(() =>
  currentStepIndex.value >= 0 && currentStepIndex.value < steps.value.length
    ? steps.value[currentStepIndex.value]
    : null
)

const completedCount = computed(() => steps.value.filter((s) => ['success', 'fail', 'skipped'].includes(s.status)).length)
const successCount = computed(() => steps.value.filter((s) => s.status === 'success').length)
const failCount = computed(() => steps.value.filter((s) => s.status === 'fail').length)
const skippedCount = computed(() => steps.value.filter((s) => s.status === 'skipped').length)
const hasMoreSteps = computed(() => currentStepIndex.value < steps.value.length - 1)
const isStepReady = computed(() => activeStep.value?.status === 'active')
const isStepDone = computed(() => activeStep.value && ['success', 'fail', 'skipped'].includes(activeStep.value.status))

// ─── Report computeds ────────────────────────────────────

const testComplete = computed(() => isStepDone.value && !hasMoreSteps.value)

const testTotalElapsed = computed(() =>
  steps.value.reduce((sum, s) => sum + (s.elapsed ?? 0), 0)
)

const failedSteps = computed(() => steps.value.filter(s => s.status === 'fail'))

const typeStats = computed(() => {
  const map = new Map<string, { label: string; pass: number; fail: number; skip: number; total: number; elapsed: number }>()
  for (const s of steps.value) {
    if (!map.has(s.resourceType)) {
      map.set(s.resourceType, { label: s.resourceLabel, pass: 0, fail: 0, skip: 0, total: 0, elapsed: 0 })
    }
    const stat = map.get(s.resourceType)!
    stat.total++
    if (s.status === 'success') stat.pass++
    else if (s.status === 'fail') stat.fail++
    else if (s.status === 'skipped') stat.skip++
    stat.elapsed += s.elapsed ?? 0
  }
  return [...map.entries()].map(([key, stat]) => ({ key, ...stat }))
})

const opStats = computed(() => {
  const ops: OpType[] = ['CREATE', 'READ', 'UPDATE', 'VERIFY', 'DELETE']
  const map = new Map<OpType, { pass: number; fail: number; skip: number; total: number }>()
  for (const op of ops) map.set(op, { pass: 0, fail: 0, skip: 0, total: 0 })
  for (const s of steps.value) {
    const stat = map.get(s.op)!
    stat.total++
    if (s.status === 'success') stat.pass++
    else if (s.status === 'fail') stat.fail++
    else if (s.status === 'skipped') stat.skip++
  }
  return [...map.entries()].map(([op, stat]) => ({ op, ...stat })).filter(s => s.total > 0)
})

const overallVerdict = computed(() => {
  if (failCount.value === 0 && skippedCount.value === 0) return 'pass'
  if (failCount.value > 0) return 'fail'
  return 'partial'
})

// ─── Map ─────────────────────────────────────────────────

const mapContainer = ref<HTMLDivElement>()
let map: OlMap | null = null
const vectorSource = new VectorSource()

const TYPE_COLORS: Record<string, string> = {
  systems: '#3b82f6',
  procedures: '#f59e0b',
  deployments: '#8b5cf6',
  samplingFeatures: '#10b981',
  datastreams: '#ef4444',
  controlStreams: '#f97316',
  observations: '#06b6d4',
  commands: '#ec4899',
  subsystems: '#60a5fa',
  subdeployments: '#a78bfa',
}

const TYPE_LABELS: Record<string, string> = {
  systems: 'S',
  procedures: 'P',
  deployments: 'D',
  samplingFeatures: 'F',
  datastreams: 'DS',
  controlStreams: 'CS',
  observations: 'O',
  commands: 'Cmd',
  subsystems: 'Sub',
  subdeployments: 'SD',
}

function markerStyle(resourceType: string, phase: 'create' | 'update' | 'ghost'): Style {
  const color = TYPE_COLORS[resourceType] || '#6b7280'
  const label = TYPE_LABELS[resourceType] || '?'
  const isGhost = phase === 'ghost'
  return new Style({
    image: new CircleStyle({
      radius: isGhost ? 7 : 12,
      fill: new Fill({ color: isGhost ? 'transparent' : color }),
      stroke: new Stroke({ color, width: isGhost ? 2 : 3, lineDash: isGhost ? [4, 4] : undefined }),
    }),
    text: new OlText({
      text: isGhost ? '' : label,
      fill: new Fill({ color: '#fff' }),
      font: 'bold 11px sans-serif',
      offsetY: 1,
    }),
  })
}

function initMap() {
  if (!mapContainer.value || map) return
  map = new OlMap({
    target: mapContainer.value,
    layers: [
      new TileLayer({ source: new OSM() }),
      new VectorLayer({ source: vectorSource }),
    ],
    view: new View({
      center: fromLonLat([-77.035, 38.890]),
      zoom: 14,
    }),
  })
}

function addMarker(resourceType: string, coords: [number, number], featureId: string, phase: 'create' | 'update') {
  const existing = vectorSource.getFeatureById(featureId)
  if (existing) vectorSource.removeFeature(existing)

  if (phase === 'update') {
    const oldCoords = COORDS[resourceType]?.create
    if (oldCoords) {
      const ghostId = featureId + '-ghost'
      const existingGhost = vectorSource.getFeatureById(ghostId)
      if (existingGhost) vectorSource.removeFeature(existingGhost)
      const ghost = new OlFeature({ geometry: new OlPoint(fromLonLat(oldCoords)) })
      ghost.setId(ghostId)
      ghost.setStyle(markerStyle(resourceType, 'ghost'))
      vectorSource.addFeature(ghost)
    }
  }

  const feature = new OlFeature({ geometry: new OlPoint(fromLonLat(coords)) })
  feature.setId(featureId)
  feature.setStyle(markerStyle(resourceType, phase))
  vectorSource.addFeature(feature)

  map?.getView().animate({ center: fromLonLat(coords), duration: 600 })
}

function removeMarker(featureId: string) {
  const f = vectorSource.getFeatureById(featureId)
  if (f) vectorSource.removeFeature(f)
  const g = vectorSource.getFeatureById(featureId + '-ghost')
  if (g) vectorSource.removeFeature(g)
}

function clearMap() {
  vectorSource.clear()
}

// ─── Preview: prepare what the step WILL do ──────────────

function prepareStepPreview(step: Step) {
  const actualType = NESTED_ACTUAL_TYPE[step.resourceType] || step.resourceType
  const contentType = getContentType(actualType)

  switch (step.op) {
    case 'CREATE': {
      let parentId: string | undefined
      if (step.resourceType === 'datastreams' || step.resourceType === 'controlStreams') {
        parentId = createdIds['systems']
      }
      if (step.resourceType === 'observations') parentId = createdIds['datastreams']
      if (step.resourceType === 'commands') parentId = createdIds['controlStreams']
      // Nested hierarchy types
      if (NESTED_PARENT_TYPE[step.resourceType]) {
        parentId = createdIds[NESTED_PARENT_TYPE[step.resourceType]]
      }

      const url = getCreateUrl(step.resourceType, parentId)
      const payload = makePayload(step.resourceType, 'create')
      step.request = {
        method: 'POST',
        url,
        headers: { 'Content-Type': contentType },
        body: JSON.stringify(payload, null, 2),
      }
      break
    }
    case 'READ':
    case 'VERIFY': {
      const id = createdIds[step.resourceType]
      if (id) {
        step.request = {
          method: 'GET',
          url: getDetailUrl(actualType, id),
          headers: { 'Accept': contentType },
        }
      }
      break
    }
    case 'UPDATE': {
      const id = createdIds[step.resourceType]
      if (id) {
        const payload = makePayload(step.resourceType, 'update')
        step.request = {
          method: 'PUT',
          url: getUpdateUrl(actualType, id),
          headers: { 'Content-Type': contentType, 'Accept': contentType },
          body: JSON.stringify(payload, null, 2),
        }
      }
      break
    }
    case 'DELETE': {
      const id = createdIds[step.resourceType]
      if (id) {
        step.request = {
          method: 'DELETE',
          url: getDeleteUrl(actualType, id),
          headers: {},
        }
      }
      break
    }
  }
}

// ─── Retry Helper ────────────────────────────────────────

/** Retry an apiFetch call on transient server errors (500, 502, 503, 504). */
async function apiFetchWithRetry(
  url: string,
  options: RequestInit = {},
  retries = 1,
  delayMs = 800
): Promise<any> {
  const resp = await apiFetch(url, options)
  if (!resp.ok && retries > 0 && [500, 502, 503, 504].includes(resp.status)) {
    await new Promise(r => setTimeout(r, delayMs))
    return apiFetchWithRetry(url, options, retries - 1, delayMs * 1.5)
  }
  return resp
}

// ─── Pre-Clean: purge orphaned smoke-test resources ──────

const preCleanMessage = ref('')
const preCleanRunning = ref(false)

async function preClean() {
  preCleanRunning.value = true
  preCleanMessage.value = 'Scanning for orphaned smoke-test resources…'
  const types = ['commands', 'controlstreams', 'observations', 'datastreams',
                 'subsystems', 'subdeployments', 'samplingFeatures',
                 'deployments', 'procedures', 'systems']
  let totalDeleted = 0
  for (const type of types) {
    try {
      const listUrl = `/${type === 'subsystems' ? 'systems' : (type === 'subdeployments' ? 'deployments' : type)}?q=${SMOKE_TAG}&limit=50`
      const resp = await apiFetch(listUrl, { method: 'GET', headers: { 'Accept': 'application/json' } })
      if (!resp.ok || !resp.data?.items) continue
      for (const item of resp.data.items) {
        const id = item.id || item.properties?.id
        if (!id) continue
        const actual = type === 'subsystems' ? 'systems' : (type === 'subdeployments' ? 'deployments' : type)
        try {
          await apiFetch(`/${actual}/${id}`, { method: 'DELETE' })
          totalDeleted++
        } catch { /* best effort */ }
      }
    } catch { /* best effort */ }
  }
  preCleanMessage.value = totalDeleted > 0
    ? `Purged ${totalDeleted} orphaned resource(s)`
    : 'Server is clean — no orphans found'
  preCleanRunning.value = false
  setTimeout(() => { preCleanMessage.value = '' }, 4000)
}

// ─── Warm Up: ping server to ensure JVM / cold-start is past ──

const warmUpMessage = ref('')
const warmUpRunning = ref(false)
const warmUpReady = ref(false)

async function warmUp() {
  warmUpRunning.value = true
  warmUpReady.value = false
  warmUpMessage.value = 'Warming up server…'

  const MAX_PINGS = 6
  const READY_THRESHOLD_MS = 1500  // sub-1.5s = warm
  let consecutiveFast = 0

  for (let i = 0; i < MAX_PINGS; i++) {
    const start = performance.now()
    try {
      const resp = await apiFetch('/systems?limit=1', { method: 'GET', headers: { Accept: 'application/json' } })
      const elapsed = Math.round(performance.now() - start)
      if (resp.ok && elapsed < READY_THRESHOLD_MS) {
        consecutiveFast++
        warmUpMessage.value = `Ping ${i + 1}/${MAX_PINGS}: ${elapsed}ms ✓`
        if (consecutiveFast >= 2) {
          warmUpMessage.value = `Server ready — ${elapsed}ms response`
          warmUpReady.value = true
          warmUpRunning.value = false
          setTimeout(() => { warmUpMessage.value = '' }, 5000)
          return
        }
      } else {
        consecutiveFast = 0
        warmUpMessage.value = resp.ok
          ? `Ping ${i + 1}/${MAX_PINGS}: ${elapsed}ms (warming…)`
          : `Ping ${i + 1}/${MAX_PINGS}: ${resp.status} (retrying…)`
      }
    } catch {
      consecutiveFast = 0
      warmUpMessage.value = `Ping ${i + 1}/${MAX_PINGS}: error (retrying…)`
    }
    // Brief pause between pings
    await new Promise(r => setTimeout(r, 600))
  }

  // Finished all pings without consecutive fast responses
  warmUpMessage.value = 'Warm-up complete — server may still be sluggish'
  warmUpReady.value = true
  warmUpRunning.value = false
  setTimeout(() => { warmUpMessage.value = '' }, 5000)
}

// ─── Step Execution ──────────────────────────────────────

async function executeCurrentStep() {
  const step = activeStep.value
  if (!step || step.status !== 'active') return

  step.status = 'running'
  const start = performance.now()

  const actualType = NESTED_ACTUAL_TYPE[step.resourceType] || step.resourceType
  const contentType = getContentType(actualType)

  try {
    switch (step.op) {
      case 'CREATE': {
        let parentId: string | undefined
        if (step.resourceType === 'datastreams' || step.resourceType === 'controlStreams') {
          parentId = createdIds['systems']
          if (!parentId) { markSkipped(step, 'No parent system created — skipping', start); return }
        }
        if (step.resourceType === 'observations') {
          parentId = createdIds['datastreams']
          if (!parentId) { markSkipped(step, 'No parent datastream created — skipping', start); return }
        }
        if (step.resourceType === 'commands') {
          parentId = createdIds['controlStreams']
          if (!parentId) { markSkipped(step, 'No parent control stream created — skipping', start); return }
        }
        // Nested hierarchy types
        if (NESTED_PARENT_TYPE[step.resourceType]) {
          parentId = createdIds[NESTED_PARENT_TYPE[step.resourceType]]
          if (!parentId) { markSkipped(step, `No parent ${NESTED_PARENT_TYPE[step.resourceType]} created — skipping`, start); return }
        }

        const url = getCreateUrl(step.resourceType, parentId)
        const payload = makePayload(step.resourceType, 'create')
        const bodyStr = JSON.stringify(payload, null, 2)

        // Only send Content-Type, NOT Accept — OSH may reject Accept: application/geo+json
        // apiFetch defaults Accept to application/json which works fine
        step.request = {
          method: 'POST', url,
          headers: { 'Content-Type': contentType },
          body: bodyStr,
        }
        step.before = null

        const resp = await apiFetchWithRetry(url, {
          method: 'POST',
          headers: { 'Content-Type': contentType },
          body: bodyStr,
        })

        setResponse(step, resp)

        if (!resp.ok) {
          // Command CREATE: OSH rejects commands for API-created systems with no
          // connected driver ("Receiving system is disabled").  The JSON was parsed
          // correctly — this is a server-side limitation, not a payload error.
          const errText = resp.error || resp.statusText || ''
          if (step.resourceType === 'commands' && /rejected|disabled|not supported|no receiver|no handler|not available/i.test(errText)) {
            markSkipped(step, 'Command parsed OK — rejected by server (no connected driver)', start)
            return
          }
          markFail(step, resp.error || `${resp.status} ${resp.statusText}`, start)
          return
        }

        // Extract ID from Location header
        const location = resp.headers['location'] || ''
        const id = location.split('/').pop() || ''
        if (id) createdIds[step.resourceType] = id

        // Store the UID so UPDATE can include it (OSH requires it)
        const payload2 = JSON.parse(bodyStr)
        if (payload2?.properties?.uid) createdUids[step.resourceType] = payload2.properties.uid

        step.after = resp.data || { _smokeTest: true, id, location }
        step.status = 'success'

        // Map
        const coords = COORDS[step.resourceType]?.create
        if (coords && id) {
          step.coords = coords
          addMarker(step.resourceType, coords, `smoke-${step.resourceType}`, 'create')
        }
        break
      }

      case 'READ': {
        const id = createdIds[step.resourceType]
        if (!id) { markSkipped(step, 'No ID from CREATE — skipping', start); return }

        const url = getDetailUrl(actualType, id)
        step.request = { method: 'GET', url, headers: { 'Accept': contentType } }

        const resp = await apiFetchWithRetry(url, { method: 'GET', headers: { 'Accept': contentType } })
        setResponse(step, resp)

        if (!resp.ok) {
          markFail(step, resp.error || `${resp.status} ${resp.statusText}`, start)
        } else {
          step.before = null
          step.after = resp.data
          step.status = 'success'
          const coords = COORDS[step.resourceType]?.create
          if (coords) step.coords = coords
        }
        break
      }

      case 'UPDATE': {
        const id = createdIds[step.resourceType]
        if (!id) { markSkipped(step, 'No ID from CREATE — skipping', start); return }

        // Fetch current state as "before"
        const readUrl = getDetailUrl(actualType, id)
        const readResp = await apiFetch(readUrl, { method: 'GET', headers: { 'Accept': contentType } })
        step.before = readResp.data

        const url = getUpdateUrl(actualType, id)
        let payload = makePayload(step.resourceType, 'update')

        // For controlStreams: merge updated fields into server's current state.
        // OSH requires the 'schema' block on PUT but the GET response does NOT
        // embed the schema inline — it's a separate sub-resource at /schema.
        // Also, OSH crashes (500) if you send CREATE-format field names.
        // Workaround: fetch current state + schema separately, merge into PUT. (S-12)
        if (step.resourceType === 'controlStreams' && readResp.ok && readResp.data) {
          payload = { ...readResp.data, ...payload }
          // Fetch schema sub-resource and inject into payload
          const schemaUrl = `${readUrl}/schema`
          const schemaResp = await apiFetch(schemaUrl, { method: 'GET', headers: { 'Accept': 'application/json' } })
          if (schemaResp.ok && schemaResp.data) {
            payload.schema = schemaResp.data
          }
        }

        const bodyStr = JSON.stringify(payload, null, 2)

        step.request = {
          method: 'PUT', url,
          headers: { 'Content-Type': contentType, 'Accept': contentType },
          body: bodyStr,
        }

        const resp = await apiFetchWithRetry(url, {
          method: 'PUT',
          headers: { 'Content-Type': contentType, 'Accept': contentType },
          body: bodyStr,
        })
        setResponse(step, resp)

        if (!resp.ok) {
          // ControlStream UPDATE: OSH server bug — CommandStreamChangedEvent uses
          // raw deserialized csInfo (missing systemUID) instead of the merged
          // newCsInfo, causing "NPE: UniqueID cannot be null".  (S-13)
          if (step.resourceType === 'controlStreams' && resp.status === 500) {
            markSkipped(step, 'Known server bug: NPE in CommandStreamChangedEvent (S-13)', start)
          } else {
            markFail(step, resp.error || `${resp.status} ${resp.statusText}`, start)
          }
        } else {
          step.after = resp.data || payload
          step.status = 'success'
          const coords = COORDS[step.resourceType]?.update
          if (coords) {
            step.coords = coords
            addMarker(step.resourceType, coords, `smoke-${step.resourceType}`, 'update')
          }
        }
        break
      }

      case 'VERIFY': {
        const id = createdIds[step.resourceType]
        if (!id) { markSkipped(step, 'No ID from CREATE — skipping', start); return }

        const url = getDetailUrl(actualType, id)
        step.request = { method: 'GET', url, headers: { 'Accept': contentType } }

        const resp = await apiFetchWithRetry(url, { method: 'GET', headers: { 'Accept': contentType } })
        setResponse(step, resp)

        if (!resp.ok) {
          markFail(step, resp.error || `${resp.status} ${resp.statusText}`, start)
        } else {
          const updateStep = steps.value.find(
            (s) => s.resourceType === step.resourceType && s.op === 'UPDATE'
          )
          step.before = updateStep?.after || null
          step.after = resp.data
          step.status = 'success'
        }
        break
      }

      case 'DELETE': {
        const id = createdIds[step.resourceType]
        if (!id) { markSkipped(step, 'No ID from CREATE — skipping', start); return }

        const readUrl = getDetailUrl(actualType, id)
        const readResp = await apiFetch(readUrl, { method: 'GET', headers: { 'Accept': contentType } })
        step.before = readResp.data

        const url = getDeleteUrl(actualType, id)
        step.request = { method: 'DELETE', url, headers: {} }

        const resp = await apiFetchWithRetry(url, { method: 'DELETE' })
        setResponse(step, resp)

        if (!resp.ok) {
          markFail(step, resp.error || `${resp.status} ${resp.statusText}`, start)
        } else {
          step.after = null
          step.status = 'success'
          delete createdIds[step.resourceType]
          removeMarker(`smoke-${step.resourceType}`)
        }
        break
      }
    }
  } catch (err: any) {
    step.status = 'fail'
    step.error = err.message || 'Unknown error'
  }

  step.elapsed = performance.now() - start
}

function setResponse(step: Step, resp: any) {
  step.response = {
    status: resp.status,
    statusText: resp.statusText,
    headers: resp.headers,
    body: resp.data ? JSON.stringify(resp.data, null, 2) : (resp.error || ''),
    rawError: resp.error || undefined,
  }
}

function markSkipped(step: Step, msg: string, start: number) {
  step.status = 'skipped'
  step.error = msg
  step.elapsed = performance.now() - start
}

function markFail(step: Step, msg: string, start: number) {
  step.status = 'fail'
  step.error = msg
  step.elapsed = performance.now() - start
}

// ─── Controls ────────────────────────────────────────────

function beginTest() {
  testStarted.value = true
  currentStepIndex.value = 0
  const step = steps.value[0]
  step.status = 'active'
  prepareStepPreview(step)
}

async function executeAndWait() {
  running.value = true
  await executeCurrentStep()
  running.value = false
}

function advanceToNextStep() {
  if (!hasMoreSteps.value) return
  currentStepIndex.value++
  const step = steps.value[currentStepIndex.value]
  step.status = 'active'
  prepareStepPreview(step)
}

function skipCurrentStep() {
  const step = activeStep.value
  if (!step) return
  step.status = 'skipped'
  step.error = 'Manually skipped'
  step.elapsed = 0
}

/** Run all remaining steps automatically without manual clicks. */
async function runAllSteps() {
  if (!testStarted.value) beginTest()
  running.value = true
  while (currentStepIndex.value < steps.value.length) {
    const step = steps.value[currentStepIndex.value]
    if (step.status === 'pending') step.status = 'active'
    if (step.status === 'active') {
      prepareStepPreview(step)
      await executeCurrentStep()
    }
    // Advance to next step
    if (currentStepIndex.value < steps.value.length - 1) {
      currentStepIndex.value++
    } else {
      break
    }
  }
  running.value = false
}

async function abortAndCleanup() {
  cleanupMessage.value = ''
  const idsToDelete = Object.keys(createdIds).filter(k => createdIds[k])
  if (idsToDelete.length === 0) {
    cleanupMessage.value = 'Nothing to clean up \u2014 all resources already deleted'
    setTimeout(() => { cleanupMessage.value = '' }, 4000)
    return
  }
  running.value = true
  cleanupMessage.value = `Deleting ${idsToDelete.length} resource(s)...`
  let deleted = 0
  let failed = 0
  const deleteOrder = ['commands', 'controlStreams', 'observations', 'datastreams', 'subsystems', 'subdeployments', 'samplingFeatures', 'deployments', 'procedures', 'systems']
  for (const type of deleteOrder) {
    const id = createdIds[type]
    if (!id) continue
    try {
      const actual = NESTED_ACTUAL_TYPE[type] || type
      const url = getDeleteUrl(actual, id)
      await apiFetch(url, { method: 'DELETE' })
      delete createdIds[type]
      removeMarker(`smoke-${type}`)
      deleted++
    } catch {
      failed++
    }
  }
  running.value = false
  cleanupMessage.value = failed
    ? `Cleaned up ${deleted} resource(s), ${failed} failed`
    : `Cleaned up ${deleted} resource(s) successfully`
  setTimeout(() => { cleanupMessage.value = '' }, 5000)
}

function resetTest() {
  steps.value = buildSteps()
  currentStepIndex.value = -1
  testStarted.value = false
  running.value = false
  showReport.value = false
  warmUpReady.value = false
  warmUpMessage.value = ''
  for (const key of Object.keys(createdIds)) delete createdIds[key]
  for (const key of Object.keys(createdUids)) delete createdUids[key]
  clearMap()
}

function selectStep(step: Step) {
  // Only allow viewing completed/active steps
  const idx = steps.value.indexOf(step)
  if (idx <= currentStepIndex.value) {
    currentStepIndex.value = idx
  }
  if (step.coords && map) {
    map.getView().animate({ center: fromLonLat(step.coords), duration: 400 })
  }
}

// ─── Formatting helpers ──────────────────────────────────

function opBadgeClass(op: OpType): string {
  return { CREATE: 'op-create', READ: 'op-read', UPDATE: 'op-update', VERIFY: 'op-verify', DELETE: 'op-delete' }[op]
}

function statusIcon(status: StepStatus): string {
  return {
    pending: 'pi pi-circle',
    active: 'pi pi-arrow-right',
    running: 'pi pi-spin pi-spinner',
    success: 'pi pi-check-circle',
    fail: 'pi pi-times-circle',
    skipped: 'pi pi-minus-circle',
  }[status]
}

function statusColor(status: StepStatus): string {
  return {
    pending: '#94a3b8',
    active: '#3b82f6',
    running: '#3b82f6',
    success: '#16a34a',
    fail: '#dc2626',
    skipped: '#f59e0b',
  }[status]
}

function formatMs(ms?: number): string {
  if (ms == null) return ''
  return ms < 1000 ? `${Math.round(ms)}ms` : `${(ms / 1000).toFixed(1)}s`
}

const groupedSteps = computed(() => {
  const groups: { type: string; label: string; steps: Step[] }[] = []
  let current: (typeof groups)[0] | null = null
  for (const step of steps.value) {
    if (!current || current.type !== step.resourceType) {
      current = { type: step.resourceType, label: step.resourceLabel, steps: [] }
      groups.push(current)
    }
    current.steps.push(step)
  }
  return groups
})

// ─── Auto-scroll ─────────────────────────────────────────

function scrollToActive(el: HTMLElement) {
  nextTick(() => {
    el.scrollIntoView({ behavior: 'smooth', block: 'nearest' })
  })
}

// ─── Lifecycle ───────────────────────────────────────────

onMounted(() => { nextTick(() => initMap()) })
onUnmounted(() => { map?.setTarget(undefined); map = null })
</script>

<template>
  <div class="smoke-test">
    <!-- Top bar -->
    <div class="smoke-toolbar">
      <div class="toolbar-left">
        <h2><i class="pi pi-bolt"></i> CRUD Smoke Test</h2>
        <span v-if="testStarted" class="progress-badge">
          Step {{ currentStepIndex + 1 }}/{{ steps.length }} —
          <span style="color:#16a34a">{{ successCount }} pass</span>
          <span v-if="failCount" style="color:#dc2626"> · {{ failCount }} fail</span>
          <span v-if="skippedCount" style="color:#f59e0b"> · {{ skippedCount }} skip</span>
        </span>
      </div>
      <div class="toolbar-right">
        <!-- Pre-clean + Warm Up (leftmost, before divider) -->
        <div class="action-slot action-slot-cleanup">
          <button v-if="!testStarted" class="btn btn-warning" @click="preClean" :disabled="preCleanRunning || warmUpRunning || running" title="Purge orphaned smoke-test resources from previous failed runs">
            <i :class="preCleanRunning ? 'pi pi-spin pi-spinner' : 'pi pi-eraser'"></i> Pre-Clean
          </button>
          <button v-else-if="testStarted" class="btn btn-danger" @click="abortAndCleanup" :disabled="running">
            <i class="pi pi-trash"></i> Cleanup
          </button>
          <span v-else class="btn-placeholder"></span>
          <span v-if="cleanupMessage" class="cleanup-message">{{ cleanupMessage }}</span>
          <span v-if="preCleanMessage" class="cleanup-message">{{ preCleanMessage }}</span>
        </div>

        <!-- Warm Up -->
        <div class="action-slot action-slot-cleanup">
          <button v-if="!testStarted" class="btn btn-warmup" @click="warmUp" :disabled="warmUpRunning || preCleanRunning || running" title="Ping the server a few times to ensure it is past cold-start">
            <i :class="warmUpRunning ? 'pi pi-spin pi-spinner' : (warmUpReady ? 'pi pi-check-circle' : 'pi pi-sun')"></i>
            {{ warmUpReady ? 'Ready' : 'Warm Up' }}
          </button>
          <span v-else class="btn-placeholder"></span>
          <span v-if="warmUpMessage" class="cleanup-message">{{ warmUpMessage }}</span>
        </div>

        <div class="toolbar-divider"></div>

        <!-- Fixed-width action slot so buttons never shift -->
        <div class="action-slot">
          <button v-if="!testStarted" class="btn btn-primary" @click="beginTest">
            <i class="pi pi-play"></i> Begin Test
          </button>
          <button v-else-if="isStepReady" class="btn btn-execute" @click="executeAndWait" :disabled="running">
            <i class="pi pi-bolt"></i> Execute Step
          </button>
          <button v-else-if="isStepDone && hasMoreSteps" class="btn btn-primary" @click="advanceToNextStep">
            <i class="pi pi-arrow-right"></i> Next Step
          </button>
          <span v-else-if="isStepDone && !hasMoreSteps && !showReport" class="done-badge">
            <i class="pi pi-check-circle"></i> Test Complete
          </span>
          <button v-else-if="showReport" class="btn btn-secondary" @click="showReport = false">
            <i class="pi pi-arrow-left"></i> Back to Steps
          </button>
          <span v-else class="btn-placeholder"></span>
        </div>

        <!-- Run All / Skip / View Report -->
        <div class="action-slot" :class="{ 'action-slot-sm': !testComplete }">
          <button v-if="!testStarted" class="btn btn-success" @click="runAllSteps" :disabled="running || preCleanRunning || warmUpRunning">
            <i class="pi pi-forward"></i> Run All
          </button>
          <button v-else-if="isStepReady" class="btn btn-secondary" @click="skipCurrentStep">
            <i class="pi pi-angle-double-right"></i> Skip
          </button>
          <button v-else-if="testComplete && !showReport" class="btn btn-primary" @click="showReport = true">
            <i class="pi pi-chart-bar"></i> View Report
          </button>
          <span v-else class="btn-placeholder"></span>
        </div>
        <button class="btn btn-secondary" @click="resetTest" :disabled="running">
          <i class="pi pi-refresh"></i> Reset
        </button>
      </div>
    </div>

    <!-- Tri-panel -->
    <div class="panels" :class="{ 'report-mode': showReport }">
      <!-- LEFT: Test Plan -->
      <div class="panel panel-plan">
        <div class="panel-header">Test Plan</div>
        <div class="plan-list">
          <div v-for="group in groupedSteps" :key="group.type" class="plan-group">
            <div class="plan-group-label">{{ group.label }}</div>
            <div
              v-for="step in group.steps"
              :key="step.id"
              :ref="(el) => { if (step === activeStep && el) scrollToActive(el as HTMLElement) }"
              class="plan-step"
              :class="{ active: step === activeStep, clickable: steps.indexOf(step) <= currentStepIndex }"
              @click="selectStep(step)"
            >
              <i :class="statusIcon(step.status)" :style="{ color: statusColor(step.status) }"></i>
              <span class="op-badge" :class="opBadgeClass(step.op)">{{ step.op }}</span>
              <span v-if="step.elapsed != null" class="step-time">{{ formatMs(step.elapsed) }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- CENTER: Request / Response -->
      <template v-if="!showReport">
      <div class="panel panel-detail">
        <div class="panel-header">Request / Response</div>

        <!-- Not started -->
        <div v-if="!testStarted" class="panel-empty">
          <div class="empty-hero">
            <i class="pi pi-bolt" style="font-size:2rem;color:#3b82f6"></i>
            <p>Click <b>Begin Test</b> to start the CRUD smoke test.</p>
            <p class="empty-sub">Each step requires your approval before executing.<br>
              You'll see a preview of the request, then click <b>Execute Step</b> to send it.</p>
          </div>
        </div>

        <!-- Active step content -->
        <div v-else-if="activeStep" class="detail-content">
          <!-- Step header -->
          <div class="step-header-card">
            <span class="op-badge op-badge-lg" :class="opBadgeClass(activeStep.op)">{{ activeStep.op }}</span>
            <span class="step-resource-label">{{ activeStep.resourceLabel }}</span>
            <span v-if="activeStep.status === 'running'" class="running-indicator">
              <i class="pi pi-spin pi-spinner"></i> Executing...
            </span>
            <span v-if="activeStep.status === 'active'" class="ready-indicator">
              Ready — review below, then click Execute Step
            </span>
            <span v-if="activeStep.status === 'success'" class="success-indicator">
              <i class="pi pi-check-circle"></i> Success
            </span>
            <span v-if="activeStep.status === 'fail'" class="fail-indicator">
              <i class="pi pi-times-circle"></i> Failed
            </span>
            <span v-if="activeStep.status === 'skipped'" class="skip-indicator">
              <i class="pi pi-minus-circle"></i> Skipped
            </span>
            <span v-if="activeStep.elapsed != null" class="elapsed">{{ formatMs(activeStep.elapsed) }}</span>
          </div>

          <!-- Request preview / actual -->
          <div v-if="activeStep.request" class="detail-section">
            <div class="section-label">
              {{ activeStep.status === 'active' ? 'Request Preview' : 'Request Sent' }}
            </div>
            <div class="http-method">{{ activeStep.request.method }} {{ activeStep.request.url }}</div>
            <div class="http-headers">
              <div v-for="(v, k) in activeStep.request.headers" :key="k" class="header-line">
                <span class="header-key">{{ k }}:</span> {{ v }}
              </div>
            </div>
            <pre v-if="activeStep.request.body" class="http-body">{{ activeStep.request.body }}</pre>
          </div>

          <!-- No request (skipped before preview) -->
          <div v-if="!activeStep.request && activeStep.status === 'skipped'" class="detail-section warn-section">
            <div class="section-label"><i class="pi pi-info-circle"></i> Skipped</div>
            <p class="skip-reason">{{ activeStep.error }}</p>
          </div>

          <!-- Response -->
          <div v-if="activeStep.response" class="detail-section">
            <div class="section-label">
              Response
              <span
                class="status-badge"
                :class="activeStep.response.status < 300 ? 'status-ok' : 'status-err'"
              >
                {{ activeStep.response.status }} {{ activeStep.response.statusText }}
              </span>
            </div>
            <div class="http-headers">
              <div v-for="(v, k) in activeStep.response.headers" :key="k" class="header-line">
                <span class="header-key">{{ k }}:</span> {{ v }}
              </div>
            </div>
            <pre v-if="activeStep.response.body" class="http-body">{{ activeStep.response.body }}</pre>
            <div v-else class="empty-body">(empty body)</div>
          </div>

          <!-- Error detail -->
          <div v-if="activeStep.error && activeStep.status === 'fail'" class="detail-section error-section">
            <div class="section-label" style="color:#dc2626"><i class="pi pi-exclamation-triangle"></i> Error Detail</div>
            <pre class="error-body">{{ activeStep.error }}</pre>
          </div>

          <!-- Before / After diff -->
          <div v-if="activeStep.before !== undefined || activeStep.after !== undefined" class="detail-section">
            <div class="section-label">State Change</div>
            <div class="diff-panels">
              <div class="diff-pane">
                <div class="diff-label">Before</div>
                <pre class="diff-body">{{ activeStep.before ? JSON.stringify(activeStep.before, null, 2) : '(none)' }}</pre>
              </div>
              <div class="diff-pane">
                <div class="diff-label">After</div>
                <pre class="diff-body">{{ activeStep.after ? JSON.stringify(activeStep.after, null, 2) : '(deleted)' }}</pre>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- RIGHT: Map -->
      <div class="panel panel-map">
        <div class="panel-header">Map View</div>
        <div ref="mapContainer" class="map-container"></div>
        <div class="map-legend">
          <div v-for="type in ['systems', 'procedures', 'deployments', 'samplingFeatures', 'observations']" :key="type" class="legend-item">
            <span class="legend-dot" :style="{ background: TYPE_COLORS[type] }"></span>
            <span class="legend-label">{{ type }}</span>
          </div>
        </div>
      </div>
      </template>

      <!-- REPORT VIEW (replaces center + right panels) -->
      <div v-else class="panel panel-report">
        <div class="panel-header">Test Report</div>
        <div class="report-content">

          <!-- Verdict Banner -->
          <div class="report-verdict" :class="`verdict-${overallVerdict}`">
            <i :class="overallVerdict === 'pass' ? 'pi pi-check-circle' : overallVerdict === 'fail' ? 'pi pi-times-circle' : 'pi pi-exclamation-circle'"></i>
            <span v-if="overallVerdict === 'pass'">All Steps Passed</span>
            <span v-else-if="overallVerdict === 'fail'">Failures Detected</span>
            <span v-else>Completed with Skips</span>
          </div>

          <!-- Summary Cards -->
          <div class="report-summary-cards">
            <div class="summary-card card-total">
              <div class="card-number">{{ steps.length }}</div>
              <div class="card-label">Total Steps</div>
            </div>
            <div class="summary-card card-pass">
              <div class="card-number">{{ successCount }}</div>
              <div class="card-label">Passed</div>
            </div>
            <div class="summary-card card-fail">
              <div class="card-number">{{ failCount }}</div>
              <div class="card-label">Failed</div>
            </div>
            <div class="summary-card card-skip">
              <div class="card-number">{{ skippedCount }}</div>
              <div class="card-label">Skipped</div>
            </div>
            <div class="summary-card card-time">
              <div class="card-number">{{ formatMs(testTotalElapsed) }}</div>
              <div class="card-label">Total Time</div>
            </div>
          </div>

          <!-- Server Info -->
          <div class="report-server-info">
            <i class="pi pi-server"></i>
            {{ connection.url }}
          </div>

          <!-- Operation Breakdown -->
          <div class="report-section">
            <div class="report-section-title"><i class="pi pi-list"></i> Operation Breakdown</div>
            <div class="report-op-grid">
              <div v-for="stat in opStats" :key="stat.op" class="report-op-row">
                <span class="op-badge" :class="opBadgeClass(stat.op)">{{ stat.op }}</span>
                <div class="report-op-bar-wrapper">
                  <div class="report-op-bar">
                    <div v-if="stat.pass" class="bar-segment bar-pass" :style="{ width: (stat.pass / stat.total * 100) + '%' }"></div>
                    <div v-if="stat.fail" class="bar-segment bar-fail" :style="{ width: (stat.fail / stat.total * 100) + '%' }"></div>
                    <div v-if="stat.skip" class="bar-segment bar-skip" :style="{ width: (stat.skip / stat.total * 100) + '%' }"></div>
                  </div>
                </div>
                <span class="report-op-counts">
                  <span style="color:#16a34a">{{ stat.pass }}</span>
                  <span v-if="stat.fail" style="color:#dc2626"> / {{ stat.fail }}</span>
                  <span v-if="stat.skip" style="color:#f59e0b"> / {{ stat.skip }}</span>
                </span>
              </div>
            </div>
          </div>

          <!-- Per-Resource-Type Table -->
          <div class="report-section">
            <div class="report-section-title"><i class="pi pi-th-large"></i> Results by Resource Type</div>
            <table class="report-table">
              <thead>
                <tr>
                  <th>Resource Type</th>
                  <th class="col-num">Pass</th>
                  <th class="col-num">Fail</th>
                  <th class="col-num">Skip</th>
                  <th class="col-num">Time</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="stat in typeStats" :key="stat.key">
                  <td>
                    <span class="type-dot" :style="{ background: TYPE_COLORS[stat.key] || '#6b7280' }"></span>
                    {{ stat.label }}
                  </td>
                  <td class="col-num col-pass">{{ stat.pass }}</td>
                  <td class="col-num" :class="{ 'col-fail': stat.fail > 0 }">{{ stat.fail }}</td>
                  <td class="col-num" :class="{ 'col-skip': stat.skip > 0 }">{{ stat.skip }}</td>
                  <td class="col-num col-time">{{ formatMs(stat.elapsed) }}</td>
                </tr>
              </tbody>
            </table>
          </div>

          <!-- Failures Detail -->
          <div v-if="failedSteps.length" class="report-section">
            <div class="report-section-title" style="color:#dc2626"><i class="pi pi-exclamation-triangle"></i> Failures ({{ failedSteps.length }})</div>
            <div v-for="step in failedSteps" :key="step.id" class="report-failure-card">
              <div class="failure-header">
                <span class="op-badge" :class="opBadgeClass(step.op)">{{ step.op }}</span>
                <span class="failure-resource">{{ step.resourceLabel }}</span>
                <span v-if="step.response" class="status-badge status-err">
                  {{ step.response.status }} {{ step.response.statusText }}
                </span>
                <span v-if="step.elapsed != null" class="elapsed">{{ formatMs(step.elapsed) }}</span>
              </div>
              <div v-if="step.request" class="failure-url">
                {{ step.request.method }} {{ step.request.url }}
              </div>
              <pre v-if="step.error" class="failure-error">{{ step.error }}</pre>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.smoke-test {
  display: flex;
  flex-direction: column;
  height: calc(100vh - 56px);
  overflow: hidden;
}

/* ── Toolbar ──────────────────────── */
.smoke-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.5rem 1rem;
  border-bottom: 1px solid #e2e8f0;
  background: #f8fafc;
  flex-shrink: 0;
  flex-wrap: wrap;
  gap: 0.5rem;
}
.toolbar-left {
  display: flex;
  align-items: center;
  gap: 1rem;
}
.toolbar-left h2 {
  margin: 0;
  font-size: 1.1rem;
  display: flex;
  align-items: center;
  gap: 0.4rem;
}
.toolbar-right {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}
.action-slot {
  width: 150px;
  display: flex;
  justify-content: flex-end;
}
.action-slot-sm {
  width: 70px;
}
.action-slot-cleanup {
  width: 110px;
  position: relative;
}
.cleanup-message {
  position: absolute;
  top: 100%;
  left: 0;
  margin-top: 4px;
  font-size: 0.75rem;
  color: #64748b;
  white-space: nowrap;
  animation: fadeIn 0.2s ease;
}
@keyframes fadeIn {
  from { opacity: 0; transform: translateY(-4px); }
  to { opacity: 1; transform: translateY(0); }
}
.btn-placeholder {
  display: block;
  width: 100%;
  height: 32px;
}
.toolbar-divider {
  width: 1px;
  height: 20px;
  background: #cbd5e1;
  margin: 0 0.25rem;
}
.progress-badge {
  font-size: 0.85rem;
  font-weight: 600;
}
.done-badge {
  display: inline-flex;
  align-items: center;
  gap: 0.3rem;
  color: #16a34a;
  font-weight: 700;
  font-size: 0.85rem;
}
.btn {
  display: inline-flex;
  align-items: center;
  gap: 0.3rem;
  padding: 0.4rem 0.9rem;
  border: none;
  border-radius: 6px;
  font-size: 0.85rem;
  font-weight: 600;
  cursor: pointer;
  transition: background 0.15s;
}
.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
.btn-primary { background: #3b82f6; color: #fff; }
.btn-primary:hover:not(:disabled) { background: #2563eb; }
.btn-execute { background: #16a34a; color: #fff; font-size: 0.9rem; padding: 0.45rem 1.1rem; }
.btn-execute:hover:not(:disabled) { background: #15803d; }
.btn-secondary { background: #e2e8f0; color: #334155; }
.btn-secondary:hover:not(:disabled) { background: #cbd5e1; }
.btn-danger { background: #dc2626; color: #fff; }
.btn-danger:hover:not(:disabled) { background: #b91c1c; }
.btn-success { background: #16a34a; color: #fff; }
.btn-success:hover:not(:disabled) { background: #15803d; }
.btn-warning { background: #d97706; color: #fff; }
.btn-warning:hover:not(:disabled) { background: #b45309; }
.btn-warmup { background: #f59e0b; color: #fff; }
.btn-warmup:hover:not(:disabled) { background: #d97706; }

/* ── Panels ───────────────────────── */
.panels {
  display: grid;
  grid-template-columns: 220px 1fr 1fr;
  flex: 1;
  overflow: hidden;
}
.panel {
  display: flex;
  flex-direction: column;
  border-right: 1px solid #e2e8f0;
  overflow: hidden;
}
.panel:last-child { border-right: none; }
.panel-header {
  padding: 0.5rem 0.75rem;
  font-weight: 700;
  font-size: 0.82rem;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: #64748b;
  border-bottom: 1px solid #e2e8f0;
  background: #f1f5f9;
  flex-shrink: 0;
}

/* ── Left: Plan ───────────────────── */
.plan-list {
  overflow-y: auto;
  flex: 1;
  padding: 0.25rem 0;
}
.plan-group {
  margin-bottom: 0.25rem;
}
.plan-group-label {
  padding: 0.4rem 0.75rem 0.2rem;
  font-size: 0.72rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: #94a3b8;
}
.plan-step {
  display: flex;
  align-items: center;
  gap: 0.4rem;
  padding: 0.35rem 0.75rem;
  font-size: 0.82rem;
  border-left: 3px solid transparent;
  transition: background 0.15s;
  opacity: 0.5;
}
.plan-step.clickable {
  cursor: pointer;
  opacity: 1;
}
.plan-step.clickable:hover { background: #f1f5f9; }
.plan-step.active {
  background: #eff6ff;
  border-left-color: #3b82f6;
  opacity: 1;
}
.step-time {
  margin-left: auto;
  font-size: 0.72rem;
  color: #94a3b8;
}

/* ── Op Badges ────────────────────── */
.op-badge {
  display: inline-block;
  padding: 0.1rem 0.4rem;
  border-radius: 4px;
  font-size: 0.68rem;
  font-weight: 700;
  letter-spacing: 0.04em;
}
.op-badge-lg {
  font-size: 0.82rem;
  padding: 0.2rem 0.6rem;
}
.op-create { background: #dcfce7; color: #15803d; }
.op-read { background: #dbeafe; color: #1d4ed8; }
.op-update { background: #fef3c7; color: #a16207; }
.op-verify { background: #e0e7ff; color: #4338ca; }
.op-delete { background: #f0e6ff; color: #7c3aed; }

/* ── Center: Detail ───────────────── */
.panel-detail {
  overflow: hidden;
  display: flex;
  flex-direction: column;
}
.panel-empty {
  display: flex;
  align-items: center;
  justify-content: center;
  flex: 1;
}
.empty-hero {
  text-align: center;
  color: #64748b;
}
.empty-hero p { margin: 0.5rem 0; font-size: 0.95rem; }
.empty-sub { font-size: 0.82rem; color: #94a3b8; }
.detail-content {
  overflow-y: auto;
  flex: 1;
  padding: 0.75rem;
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}
.step-header-card {
  display: flex;
  align-items: center;
  gap: 0.6rem;
  padding: 0.6rem 0.75rem;
  background: #f8fafc;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  flex-wrap: wrap;
}
.step-resource-label {
  font-weight: 700;
  font-size: 1rem;
}
.ready-indicator { color: #3b82f6; font-size: 0.82rem; }
.running-indicator { color: #3b82f6; font-size: 0.82rem; }
.success-indicator { color: #16a34a; font-size: 0.85rem; font-weight: 600; }
.fail-indicator { color: #dc2626; font-size: 0.85rem; font-weight: 600; }
.skip-indicator { color: #f59e0b; font-size: 0.85rem; font-weight: 600; }
.elapsed {
  font-size: 0.75rem;
  color: #94a3b8;
  margin-left: auto;
}
.detail-section {
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  padding: 0.6rem 0.75rem;
  background: #fff;
}
.section-label {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-weight: 700;
  font-size: 0.85rem;
  margin-bottom: 0.4rem;
}
.http-method {
  font-family: 'Consolas', 'Monaco', monospace;
  font-size: 0.85rem;
  font-weight: 700;
  color: #1e293b;
  padding: 0.3rem 0;
  border-bottom: 1px solid #f1f5f9;
  word-break: break-all;
}
.http-headers {
  font-family: 'Consolas', 'Monaco', monospace;
  font-size: 0.72rem;
  color: #64748b;
  padding: 0.25rem 0;
}
.header-line { line-height: 1.5; }
.header-key { color: #475569; font-weight: 600; }
.http-body {
  background: #f8fafc;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  padding: 0.5rem;
  font-size: 0.75rem;
  overflow-x: auto;
  max-height: 280px;
  overflow-y: auto;
  margin: 0.3rem 0 0;
  white-space: pre-wrap;
  word-break: break-word;
}
.empty-body {
  color: #94a3b8;
  font-style: italic;
  font-size: 0.82rem;
  padding: 0.3rem 0;
}
.status-badge {
  padding: 0.1rem 0.5rem;
  border-radius: 4px;
  font-size: 0.75rem;
  font-weight: 700;
}
.status-ok { background: #dcfce7; color: #15803d; }
.status-err { background: #fee2e2; color: #dc2626; }
.error-section {
  border-color: #fecaca;
  background: #fef2f2;
}
.error-body {
  font-size: 0.78rem;
  color: #dc2626;
  white-space: pre-wrap;
  word-break: break-word;
  margin: 0;
}
.warn-section {
  border-color: #fde68a;
  background: #fffbeb;
}
.skip-reason {
  margin: 0;
  font-size: 0.85rem;
  color: #a16207;
}

/* ── Diff panels ──────────────────── */
.diff-panels {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 0.5rem;
}
.diff-pane {
  overflow: hidden;
}
.diff-label {
  font-size: 0.72rem;
  font-weight: 700;
  text-transform: uppercase;
  color: #64748b;
  margin-bottom: 0.25rem;
}
.diff-body {
  background: #f8fafc;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  padding: 0.5rem;
  font-size: 0.72rem;
  overflow: auto;
  max-height: 200px;
  margin: 0;
  white-space: pre-wrap;
  word-break: break-word;
}

/* ── Right: Map ───────────────────── */
.panel-map {
  display: flex;
  flex-direction: column;
}
.map-container {
  flex: 1;
  min-height: 0;
}
.map-legend {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  padding: 0.4rem 0.75rem;
  background: #f8fafc;
  border-top: 1px solid #e2e8f0;
  flex-shrink: 0;
}
.legend-item {
  display: flex;
  align-items: center;
  gap: 0.25rem;
  font-size: 0.7rem;
  color: #64748b;
}
.legend-dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  flex-shrink: 0;
}

/* ── Report Panel ─────────────────── */
.report-mode {
  grid-template-columns: 220px 1fr !important;
}
.panel-report {
  overflow-y: auto;
}
.report-content {
  padding: 1rem 1.25rem;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

/* Verdict Banner */
.report-verdict {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  padding: 0.75rem 1rem;
  border-radius: 8px;
  font-size: 1.1rem;
  font-weight: 700;
}
.verdict-pass {
  background: #dcfce7;
  color: #15803d;
  border: 1px solid #bbf7d0;
}
.verdict-fail {
  background: #fee2e2;
  color: #dc2626;
  border: 1px solid #fecaca;
}
.verdict-partial {
  background: #fef3c7;
  color: #a16207;
  border: 1px solid #fde68a;
}

/* Summary Cards */
.report-summary-cards {
  display: flex;
  gap: 0.75rem;
  flex-wrap: wrap;
}
.summary-card {
  flex: 1;
  min-width: 100px;
  padding: 0.75rem 1rem;
  border-radius: 8px;
  text-align: center;
  border: 1px solid #e2e8f0;
}
.card-number {
  font-size: 1.5rem;
  font-weight: 800;
  line-height: 1.2;
}
.card-label {
  font-size: 0.72rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  margin-top: 0.15rem;
}
.card-total { background: #f8fafc; }
.card-total .card-number { color: #1e293b; }
.card-total .card-label { color: #64748b; }
.card-pass { background: #f0fdf4; }
.card-pass .card-number { color: #16a34a; }
.card-pass .card-label { color: #15803d; }
.card-fail { background: #fef2f2; }
.card-fail .card-number { color: #dc2626; }
.card-fail .card-label { color: #b91c1c; }
.card-skip { background: #fffbeb; }
.card-skip .card-number { color: #f59e0b; }
.card-skip .card-label { color: #a16207; }
.card-time { background: #f0f9ff; }
.card-time .card-number { color: #0284c7; font-size: 1.15rem; }
.card-time .card-label { color: #0369a1; }

/* Server info */
.report-server-info {
  display: flex;
  align-items: center;
  gap: 0.4rem;
  font-size: 0.82rem;
  color: #64748b;
  padding: 0.4rem 0.75rem;
  background: #f8fafc;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  font-family: 'Consolas', 'Monaco', monospace;
}

/* Report Sections */
.report-section {
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  padding: 0.75rem;
  background: #fff;
}
.report-section-title {
  display: flex;
  align-items: center;
  gap: 0.4rem;
  font-weight: 700;
  font-size: 0.85rem;
  margin-bottom: 0.6rem;
  color: #334155;
}

/* Operation Breakdown */
.report-op-grid {
  display: flex;
  flex-direction: column;
  gap: 0.4rem;
}
.report-op-row {
  display: flex;
  align-items: center;
  gap: 0.6rem;
}
.report-op-bar-wrapper {
  flex: 1;
}
.report-op-bar {
  display: flex;
  height: 18px;
  border-radius: 4px;
  overflow: hidden;
  background: #f1f5f9;
}
.bar-segment {
  min-width: 2px;
  transition: width 0.3s ease;
}
.bar-pass { background: #4ade80; }
.bar-fail { background: #f87171; }
.bar-skip { background: #fbbf24; }
.report-op-counts {
  font-size: 0.78rem;
  font-weight: 600;
  min-width: 50px;
  text-align: right;
}

/* Resource Type Table */
.report-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.82rem;
}
.report-table th {
  text-align: left;
  padding: 0.4rem 0.6rem;
  font-size: 0.72rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  color: #64748b;
  border-bottom: 2px solid #e2e8f0;
}
.report-table td {
  padding: 0.45rem 0.6rem;
  border-bottom: 1px solid #f1f5f9;
}
.report-table tbody tr:hover {
  background: #f8fafc;
}
.col-num {
  text-align: center;
  font-weight: 600;
  min-width: 50px;
}
.col-pass { color: #16a34a; }
.col-fail { color: #dc2626; }
.col-skip { color: #f59e0b; }
.col-time { color: #64748b; font-size: 0.75rem; }
.type-dot {
  display: inline-block;
  width: 8px;
  height: 8px;
  border-radius: 50%;
  margin-right: 0.35rem;
  vertical-align: middle;
}

/* Failure Cards */
.report-failure-card {
  border: 1px solid #fecaca;
  background: #fef2f2;
  border-radius: 8px;
  padding: 0.6rem 0.75rem;
  margin-bottom: 0.5rem;
}
.report-failure-card:last-child { margin-bottom: 0; }
.failure-header {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  flex-wrap: wrap;
  margin-bottom: 0.3rem;
}
.failure-resource {
  font-weight: 700;
  font-size: 0.9rem;
}
.failure-url {
  font-family: 'Consolas', 'Monaco', monospace;
  font-size: 0.75rem;
  color: #64748b;
  margin-bottom: 0.3rem;
  word-break: break-all;
}
.failure-error {
  font-size: 0.75rem;
  color: #dc2626;
  background: #fff;
  border: 1px solid #fecaca;
  border-radius: 6px;
  padding: 0.4rem 0.6rem;
  margin: 0;
  white-space: pre-wrap;
  word-break: break-word;
  max-height: 160px;
  overflow-y: auto;
}

/* ── Responsive ───────────────────── */
@media (max-width: 1000px) {
  .panels {
    grid-template-columns: 180px 1fr;
    grid-template-rows: 1fr 300px;
  }
  .panels.report-mode {
    grid-template-rows: 1fr;
  }
  .panel-plan { grid-row: 1 / 3; }
  .panels.report-mode .panel-plan { grid-row: auto; }
  .panel-map { border-right: none; border-top: 1px solid #e2e8f0; }
}
@media (max-width: 700px) {
  .panels {
    grid-template-columns: 1fr;
    grid-template-rows: 200px 1fr 250px;
  }
  .panels.report-mode {
    grid-template-columns: 1fr;
    grid-template-rows: 200px 1fr;
  }
  .panel-plan { grid-row: auto; border-right: none; border-bottom: 1px solid #e2e8f0; }
  .report-summary-cards { flex-direction: column; }
}
</style>
